const API_URL=(import.meta.env.VITE_API_URL||'https://riskiq-api-v2-production.up.railway.app').replace(/\/$/,'')
async function request(url,options={}){const response=await fetch(`${API_URL}${url}`,options);const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.detail?.message||data.detail||`API error ${response.status}`);return data}
const activeDatasetId=()=>{try{return JSON.parse(localStorage.getItem('riskiq.activeDataset')||'null')?.dataset_id||''}catch{return ''}}
export const runWorkspace=p=>request('/api/v1/workspace/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)})
export async function discoverFile(file){const f=new FormData();f.append('file',file);return request('/api/v1/data/discover',{method:'POST',body:f})
}
export async function ingestFile(file,mappings,datasetId=''){const f=new FormData();f.append('file',file);f.append('mappings',JSON.stringify(mappings));if(datasetId)f.append('dataset_id',datasetId);return request('/api/v1/data/ingest',{method:'POST',body:f)}
}
export const databaseHealth=()=>request('/api/v1/data/health');export const listDatasets=()=>request('/api/v1/datasets');export const getDataset=id=>request(`/api/v1/datasets/${encodeURIComponent(id)}`);export const getDatasetHistory=id=>request(`/api/v1/datasets/${encodeURIComponent(id)}/history`);export const getDatasetPortfolio=id=>request(`/api/v1/datasets/${encodeURIComponent(id)}/portfolio`);export const getDatasetRecords=id=>request(`/api/v1/datasets/${encodeURIComponent(id)}/records`)
export const analyzePortfolio=rows=>request('/api/v1/portfolio/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(rows)});export const buildSnapshot=p=>request('/api/v1/portfolio/snapshot',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)})
function normalizeDatasetResult(result){const deterministic=result?.risk_analytics?.deterministic;if(!deterministic)return result;const par=deterministic.par||{};const snapshot={...(result.snapshot||{}),active_loans:deterministic.loan_count,outstanding_balance:deterministic.exposure,par7:Number(par.par7?.ratio||0),par30:Number(par.par30?.ratio||0),par60:Number(par.par60?.ratio||0),par90:Number(par.par90?.ratio||0)};const analysis={...(result.analysis||{})};if(!analysis.drivers?.length&&deterministic.drivers?.length)analysis.drivers=deterministic.drivers;return {...result,snapshot,analysis}}
export const runDataset=async(id,payload={})=>normalizeDatasetResult(await request(`/api/v1/datasets/${encodeURIComponent(id)}/run`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}));export const runSimulator=payload=>{const dataset_id=activeDatasetId();return request('/api/v1/simulator/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,dataset_id})})};export const runNPL=rows=>request('/api/v1/risk/npl',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(rows)});export const askCopilot=payload=>{const dataset_id=activeDatasetId()||payload?.dataset_id||payload?.risk_facts?.dataset_id||'';return request('/api/v1/ai/copilot',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,dataset_id})})}
export const listDecisionRules=(datasetId='')=>request(`/api/v1/decision-builder/rules${datasetId?`?dataset_id=${encodeURIComponent(datasetId)}`:''}`);export const validateDecisionRule=rule=>request('/api/v1/decision-builder/validate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(rule)});export const compileDecisionRule=rule=>request('/api/v1/decision-builder/compile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(rule)});export const saveDecisionRule=(rule,datasetId='')=>request('/api/v1/decision-builder/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rule,dataset_id:datasetId||activeDatasetId()})});export const evaluateDecisionRule=(rule,facts)=>request('/api/v1/decision-builder/evaluate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rule,facts})});export const evaluateDecisionFormulas=(formulas,facts)=>request('/api/v1/decision-builder/formula',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({formulas,facts})});export const runDecisionPipeline=payload=>request('/api/v1/decision-builder/pipeline',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});export const simulateDecisionPortfolio=payload=>{const dataset_id=payload?.dataset_id||activeDatasetId();return request('/api/v1/decision-builder/portfolio-simulate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,dataset_id})})};export const simulateActiveDecisionPortfolio=(rule,scorecard,normalization_code='',formulas={})=>simulateDecisionPortfolio({rule,scorecard,normalization_code,formulas});export const normalizeRows=(rows,code)=>request('/api/v1/decision-builder/normalize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rows,code})});export const normalizeDecisionRows=normalizeRows
export const validateDecisionScorecard=scorecard=>request('/api/v1/decision-builder/scorecard/validate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scorecard}));export const evaluateDecisionScorecard=(scorecard,facts)=>request('/api/v1/decision-builder/scorecard/evaluate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scorecard,facts})})
