import {useEffect,useMemo,useState} from 'react'
import {askCopilot,discoverFile,getDatasetHistory,ingestFile,listDatasets,runDataset,runSimulator} from './api'
import Builder from './Builder'

const pct=v=>`${(Number(v||0)*100).toFixed(1)}%`
const pp=v=>`${Number(v||0)>=0?'+':''}${(Number(v||0)*100).toFixed(1)} pp`
const money=v=>`$${Number(v||0).toLocaleString(undefined,{maximumFractionDigits:0})}`
const num=v=>Number(v||0).toLocaleString()
const labels={Dashboard:'Panel de control',Portfolio:'Cartera','Risk Analytics':'Analítica de riesgo',Decisions:'Decisiones','Decision Builder':'Constructor de decisiones','Scenario Lab':'Laboratorio de escenarios',Data:'Datos',Datasets:'Conjuntos de datos','Risk Copilot':'Copiloto de riesgo'}

function Card({children,className=''}){return <section className={`card advanced-card ${className}`}>{children}</section>}
function Badge({children,kind='neutral'}){return <span className={`badge ${kind}`}>{children}</span>}
function SectionHead({eyebrow,title,action}){return <div className="section-head"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h2>{title}</h2></div>{action}</div>}
function Metric({label,value,detail,kind=''}){return <div className="metric advanced-metric"><span>{label}</span><strong className={kind}>{value}</strong><small>{detail}</small></div>}

function severity(bucket,value){
 const n=Number(value||0)
 if(bucket==='PAR90') return n>=.02?'critical':n>=.01?'high':n>=.005?'watch':'control'
 if(bucket==='PAR60') return n>=.15?'critical':n>=.10?'high':n>=.05?'watch':'control'
 if(bucket==='PAR30') return n>=.20?'critical':n>=.10?'high':n>=.05?'watch':'control'
 return n>=.20?'critical':n>=.10?'high':n>=.05?'watch':'control'
}
const severityLabel={critical:'Crítico',high:'Alto',watch:'Vigilar',control:'Control'}

export default function AppAdvanced(){
 const [page,setPage]=useState('Dashboard'),[dataset,setDataset]=useState(null),[result,setResult]=useState(null),[datasets,setDatasets]=useState([]),[history,setHistory]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[file,setFile]=useState(null),[discovery,setDiscovery]=useState(null),[mappings,setMappings]=useState([]),[question,setQuestion]=useState(''),[answer,setAnswer]=useState(null),[shock,setShock]=useState(20),[sim,setSim]=useState(null)
 const metrics=result?.snapshot||dataset?.snapshot||{}
 const analysis=result?.analysis||{}
 const workspace=result?.workspace||{}
 const center=workspace.decision_center||result?.decision_center||{}
 const drivers=workspace.drivers?.drivers||analysis.drivers||[]
 const segments=analysis.segments||workspace.segments||[]
 const trend=history?.trend_available===true
 useEffect(()=>{loadDatasets();try{const d=JSON.parse(localStorage.getItem('riskiq.activeDataset')||'null');if(d){setDataset(d);getDatasetHistory(d.dataset_id).then(setHistory).catch(()=>{})}}catch{}},[])
 async function loadDatasets(){try{setDatasets(await listDatasets())}catch(e){console.warn(e)}}
 async function selectDataset(d){setDataset(d);setResult(null);setError('');localStorage.setItem('riskiq.activeDataset',JSON.stringify(d));try{setHistory(await getDatasetHistory(d.dataset_id))}catch{setHistory(null)}}
 async function execute(){if(!dataset?.dataset_id){setPage('Data');return}setLoading(true);setError('');try{const r=await runDataset(dataset.dataset_id);setResult(r);setDataset(d=>({...d,snapshot:r.snapshot,summary:r.analysis}));setHistory(await getDatasetHistory(dataset.dataset_id));setPage('Dashboard')}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function discover(){if(!file)return;setLoading(true);setError('');try{const r=await discoverFile(file);setDiscovery(r);setMappings((r.mapping_suggestions||[]).map(x=>({source:x.source,target:x.target,required:x.required})))}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function ingest(){if(!file||!mappings.length)return;setLoading(true);setError('');try{const r=await ingestFile(file,mappings);const d={dataset_id:r.dataset_id,source_name:file.name,...r};setDataset(d);localStorage.setItem('riskiq.activeDataset',JSON.stringify(d));const x=await runDataset(r.dataset_id);setResult(x);setDataset(z=>({...z,snapshot:x.snapshot,summary:x.analysis}));setHistory(await getDatasetHistory(r.dataset_id));await loadDatasets();setPage('Dashboard')}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function copilot(){if(!question.trim())return;setLoading(true);try{setAnswer(await askCopilot({question}))}catch(e){setAnswer({answer:e.message})}finally{setLoading(false)}}
 async function simulate(){if(!dataset?.dataset_id)return;setLoading(true);try{setSim(await runSimulator({shock_pct:shock/100,scenario_name:`Shock de mora +${shock}%`}))}catch(e){setError(e.message)}finally{setLoading(false)}}
 const nav=[['RIESGO',['Dashboard','Portfolio','Risk Analytics']],['DECISIÓN',['Decisions','Decision Builder','Scenario Lab']],['DATOS',['Data','Datasets']],['ASISTENCIA',['Risk Copilot']]]
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">R</div><div><b>RiskIQ</b><small>Risk Operating System</small></div></div><div className="portfolio-context"><span>CARTERA ACTIVA</span><strong>{dataset?.source_name||'Sin cartera'}</strong><small>{dataset?'Corte disponible para análisis':'Conecta una cartera para comenzar'}</small></div><nav>{nav.map(([group,items])=><div className="nav-group" key={group}><div className="nav-group-title">{group}</div>{items.map(item=><button key={item} className={page===item?'active':''} onClick={()=>setPage(item)}><span>{labels[item]}</span>{item==='Decisions'&&center?.counts?.total_cards>0&&<b>{center.counts.total_cards}</b>}</button>)}</div>)}</nav><div className="sidebar-footer"><span className="status-dot"/>Motor operativo<br/><small>Determinístico · auditable</small></div></aside><main className="main"><header className="topbar"><div><div className="breadcrumb">RIESGO DE CRÉDITO / {labels[page].toUpperCase()}</div><h1>{page==='Dashboard'?'Centro de riesgo':labels[page]}</h1></div><div className="topbar-actions">{dataset&&<Badge kind="ok">{dataset.source_name||'Cartera activa'}</Badge>}<button className="primary" onClick={execute} disabled={!dataset||loading}>{loading?'Analizando…':'Ejecutar análisis'}</button></div></header>{error&&<div className="error-banner">{error}</div>}{page==='Dashboard'&&<Dashboard metrics={metrics} dataset={dataset} center={center} drivers={drivers} segments={segments} history={history} trend={trend} onData={()=>setPage('Data')} onRun={execute}/>} {page==='Portfolio'&&<Portfolio metrics={metrics} analysis={analysis} segments={segments} history={history} trend={trend}/>} {page==='Risk Analytics'&&<Analytics metrics={metrics} drivers={drivers} segments={segments} history={history} trend={trend}/>} {page==='Decisions'&&<Decisions center={center} result={result} onRun={execute}/>} {page==='Decision Builder'&&<Builder/>} {page==='Scenario Lab'&&<Scenario shock={shock} setShock={setShock} sim={sim} onRun={simulate} metrics={metrics}/>} {page==='Data'&&<Data file={file} setFile={setFile} discovery={discovery} mappings={mappings} setMappings={setMappings} discover={discover} ingest={ingest}/>} {page==='Datasets'&&<Datasets items={datasets} active={dataset} onSelect={selectDataset}/>} {page==='Risk Copilot'&&<Copilot question={question} setQuestion={setQuestion} answer={answer} onAsk={copilot} loading={loading}/>}</main></div>
}

function Dashboard({metrics,dataset,center,drivers,segments,history,trend,onData,onRun}){
 if(!dataset)return <div className="page-content"><Card className="empty-state"><div><div className="eyebrow">CENTRO DE RIESGO</div><h2>Conecta una cartera de créditos</h2><p>RiskIQ construye una lectura de cartera basada en evidencia: posición, deterioro, concentración, trayectoria, drivers y decisiones.</p><button className="primary" onClick={onData}>Conectar datos</button></div></Card>
 const posture=severity('PAR90',metrics.par90);const actionable=buildActions(metrics,segments,drivers,history)
 return <div className="page-content"><div className="advanced-hero"><div><div className="eyebrow">CARTERA · CORTE ACTUAL</div><h2>{dataset.source_name||'Cartera de crédito'}</h2><p>Lectura ejecutiva de riesgo. La severidad describe el estado actual; la tendencia solo se activa con cortes comparables.</p></div><div className="posture-block"><span>ESTADO ACTUAL</span><strong>{posture==='critical'?'RIESGO CRÍTICO':posture==='high'?'RIESGO ALTO':posture==='watch'?'VIGILANCIA':'CONTROL'}</strong><small>{trend?'Tendencia disponible':'Sin histórico comparable'}</small></div></div>
 <div className="metric-grid"><Metric label="Exposición" value={money(metrics.outstanding_balance)} detail="Saldo principal pendiente"/><Metric label="Créditos" value={num(metrics.active_loans)} detail="Cartera activa"/><Metric label="PAR30" value={pct(metrics.par30)} detail="30+ días · severidad" kind={severity(metrics.par30,'PAR30')}/><Metric label="PAR60" value={pct(metrics.par60)} detail="60+ días · severidad" kind={severity(metrics.par60,'PAR60')}/><Metric label="PAR90" value={pct(metrics.par90)} detail="90+ días · severidad" kind={severity(metrics.par90,'PAR90')}/><Metric label="PAR7" value={pct(metrics.par7)} detail="Entrada a mora"/></div>
 <div className="command-grid"><Card className="where-card"><SectionHead eyebrow="1 · DÓNDE ESTAMOS" title="Posición de riesgo"/><div className="risk-matrix"><RiskRow bucket="PAR30" value={metrics.par30}/><RiskRow bucket="PAR60" value={metrics.par60}/><RiskRow bucket="PAR90" value={metrics.par90}/></div><div className="executive-facts"><div><span>Exposición en mora 30+</span><b>{money(Number(metrics.outstanding_balance||0)*Number(metrics.par30||0))}</b></div><div><span>Exposición en mora 90+</span><b>{money(Number(metrics.outstanding_balance||0)*Number(metrics.par90||0))}</b></div><div><span>Profundidad 90+/30+</span><b>{metrics.par30?`${(Number(metrics.par90)/Number(metrics.par30)*100).toFixed(1)}%`: '—'}</b></div></div></Card>
 <Card className="trend-card"><SectionHead eyebrow="2 · QUÉ ESTÁ PASANDO" title="Trayectoria y cambio" action={<Badge kind={trend?'ok':'warn'}>{trend?'COMPARABLE':'BASELINE'}</Badge>}/>{trend?<TrendPanel history={history}/>:<div className="baseline-panel"><strong>El sistema aún no puede afirmar si la cartera empeora o mejora.</strong><p>Este corte establece la línea base. Para medir velocidad de deterioro, estabilización, recuperación y migración se necesita al menos otro corte comparable.</p><div className="baseline-grid"><span>1 corte</span><span>0 comparaciones</span><span>0 alertas de tendencia</span></div></div>}</Card></div>
 <div className="command-grid"><Card><SectionHead eyebrow="3 · DÓNDE SE CONCENTRA" title="Concentración del deterioro"/><Concentration segments={segments} drivers={drivers} metrics={metrics}/></Card><Card><SectionHead eyebrow="4 · QUÉ REVISAR AHORA" title="Prioridades analíticas" action={<Badge kind={actionable.length?'warn':'ok'}>{actionable.length?`${actionable.length} PRIORIDADES`:'SIN ALERTAS'}</Badge>}/><ActionQueue actions={actionable}/></Card></div>
 <Card className="decision-strip"><div><div className="eyebrow">5 · QUÉ DEBEMOS HACER</div><h2>Plan de revisión</h2><p>{recommendation(metrics,segments,trend)}</p></div><div className="decision-actions"><button className="secondary" onClick={()=>document.getElementById('risk-actions')?.scrollIntoView({behavior:'smooth'})}>Ver evidencia</button><button className="primary" onClick={onRun}>Recalcular</button></div></Card>
 <Card className="evidence-table"><SectionHead eyebrow="EVIDENCIA" title="Indicadores de control"/><IndicatorTable metrics={metrics}/></Card></div>
}

function RiskRow({bucket,value}){const s=severity(bucket,value);return <div className="risk-row"><div><b>{bucket}</b><small>{bucket==='PAR30'?'Entrada y acumulación de mora':bucket==='PAR60'?'Deterioro intermedio':'Mora severa / pérdida potencial'}</small></div><strong>{pct(value)}</strong><Badge kind={s==='critical'?'critical':s==='high'?'warn':s==='watch'?'warn':'ok'}>{severityLabel[s]}</Badge></div>}
function TrendPanel({history}){const changes=history?.changes||{};return <div className="trend-panel"><div className="trend-head"><span>{history.previous_snapshot_date||'Corte previo'}</span><span>→</span><b>{history.current_snapshot_date||'Corte actual'}</b></div><div className="change-grid">{[['PAR30','par30'],['PAR60','par60'],['PAR90','par90'],['Exposición','outstanding_balance']].map(([label,key])=>{const d=changes[key]?.delta;return <div key={key}><span>{label}</span><b>{d==null?'—':key==='outstanding_balance'?money(d):pp(d)}</b><small>{d==null?'Sin dato':'vs. corte anterior'}</small></div>})}</div><p>{history.summary||history.interpretation}</p></div>}
function Concentration({segments,drivers,metrics}){const rows=segments.length?segments.slice(0,6):drivers.slice(0,6);if(!rows.length)return <div className="empty-inline"><strong>No hay segmentación suficiente.</strong><p>RiskIQ necesita variables de producto, segmento, región, vintage u otra dimensión analítica para localizar concentración.</p></div>;return <div className="concentration-list">{rows.map((x,i)=>{const title=x.title||x.segment||x.name||x.product||`Segmento ${i+1}`;const evidence=x.evidence||x.rationale||'';const exposure=x.exposure??x.outstanding_balance??x.balance;const rate=x.par30??x.metrics?.par30;return <div className="concentration-row" key={i}><div><b>{title}</b><small>{evidence}</small></div><div className="concentration-value">{exposure!=null&&<strong>{money(exposure)}</strong>}{rate!=null&&<span>PAR30 {pct(rate)}</span>}</div></div>})}</div>}
function ActionQueue({actions}){if(!actions.length)return <div className="baseline-panel"><strong>No se generan acciones arbitrarias.</strong><p>Con un baseline, RiskIQ prioriza lectura estructural y evita inventar deterioro temporal. Las acciones de estado actual se muestran solo cuando existe evidencia calculada.</p></div>;return <div className="action-queue">{actions.map((a,i)=><div key={i} className="action-item"><span className="action-index">0{i+1}</span><div><b>{a.title}</b><small>{a.reason}</small></div><Badge kind={a.priority==='critical'?'critical':'warn'}>{a.priority}</Badge></div>)}</div>}
function buildActions(metrics,segments,drivers,history){const actions=[];if(Number(metrics.par90)>=.02)actions.push({title:'Priorizar cartera 90+ para recuperación',reason:`PAR90 ${pct(metrics.par90)} representa una concentración severa de mora. Revisar exposición afectada, antigüedad y capacidad de recuperación.`,priority:'critical'});if(Number(metrics.par30)>=.10)actions.push({title:'Analizar entrada y acumulación de mora 30+',reason:`PAR30 ${pct(metrics.par30)} requiere segmentar por producto, vintage, canal y comportamiento de pago.`,priority:'high'});if(segments.length)actions.push({title:'Atacar primero el segmento de mayor materialidad',reason:'Ordenar segmentos por exposición y deterioro antes de distribuir recursos de cobranza.',priority:'high'});if(history?.trend_available&&history?.alerts?.length)actions.push({title:'Investigar deterioro entre cortes',reason:history.summary,priority:'high'});if(!actions.length&&drivers.length)actions.push({title:'Validar drivers observados',reason:'Revisar los factores calculados antes de modificar política o estrategia.',priority:'high'});return actions.slice(0,4)}
function recommendation(metrics,segments,trend){if(Number(metrics.par90)>=.02)return 'La prioridad es contener y recuperar la mora severa: segmentar 90+, cuantificar exposición afectada, revisar vintages y efectividad de cobranza. No asumir causalidad sin evidencia.';if(Number(metrics.par30)>=.10)return 'La prioridad es entender la entrada a mora: identificar segmentos y cohortes que explican PAR30 y validar si existe deterioro reciente.';if(segments.length)return 'La prioridad es localizar concentración: ordenar segmentos por exposición × deterioro y enfocar revisión donde el impacto económico sea mayor.';return trend?'Comparar el corte actual con el anterior y profundizar en los drivers que expliquen el cambio.':'Construir histórico comparable y, en paralelo, analizar concentración, materialidad y drivers del corte actual.'}
function IndicatorTable({metrics}){const rows=[['Exposición',money(metrics.outstanding_balance),'Saldo pendiente'],['Créditos activos',num(metrics.active_loans),'Volumen'],['PAR7',pct(metrics.par7),'Entrada a mora'],['PAR30',pct(metrics.par30),'30+ días'],['PAR60',pct(metrics.par60),'60+ días'],['PAR90',pct(metrics.par90),'90+ días']];return <div className="indicator-table"><div className="indicator-head"><span>Indicador</span><span>Valor</span><span>Lectura</span><span>Severidad</span></div>{rows.map(([a,b,c])=>{const s=a.startsWith('PAR')?severity(a,metrics[a.toLowerCase()]):'control';return <div className="indicator-row" key={a}><span>{a}</span><strong>{b}</strong><span>{c}</span><Badge kind={s==='critical'?'critical':s==='high'||s==='watch'?'warn':'ok'}>{a.startsWith('PAR')?severityLabel[s]:'Control'}</Badge></div>})}</div>}

function Portfolio({metrics,analysis,segments,history,trend}){return <div className="page-content"><SectionHead eyebrow="CARTERA" title="Posición, composición y materialidad"/><div className="metric-grid"><Metric label="Exposición" value={money(metrics.outstanding_balance)} detail="Saldo pendiente"/><Metric label="Créditos" value={num(metrics.active_loans||analysis.total_loans)} detail="Cartera activa"/><Metric label="PAR30" value={pct(metrics.par30)} detail="30+" kind={severity('PAR30',metrics.par30)}/><Metric label="PAR90" value={pct(metrics.par90)} detail="90+" kind={severity('PAR90',metrics.par90)}/></div><div className="command-grid"><Card><SectionHead eyebrow="MATERIALIDAD" title="Exposición potencialmente afectada"/><div className="materiality-grid"><div><span>30+ días</span><b>{money(Number(metrics.outstanding_balance||0)*Number(metrics.par30||0))}</b><small>{pct(metrics.par30)} de exposición</small></div><div><span>60+ días</span><b>{money(Number(metrics.outstanding_balance||0)*Number(metrics.par60||0))}</b><small>{pct(metrics.par60)} de exposición</small></div><div><span>90+ días</span><b>{money(Number(metrics.outstanding_balance||0)*Number(metrics.par90||0))}</b><small>{pct(metrics.par90)} de exposición</small></div></div></Card><Card><SectionHead eyebrow="HISTÓRICO" title="Estado de trayectoria"/><div className="baseline-panel"><strong>{trend?'Hay base para comparar cortes.':'No hay base para afirmar una trayectoria.'}</strong><p>{trend?history.summary:'Sube al menos un segundo corte comparable para habilitar deterioro, mejora, velocidad y migración.'}</p></div></Card></div><Card><SectionHead eyebrow="CONCENTRACIÓN" title="Segmentos que explican la cartera"/><Concentration segments={segments} drivers={analysis.drivers||[]}/></Card></div>}

function Analytics({metrics,drivers,segments,history,trend}){return <div className="page-content"><SectionHead eyebrow="RISK ANALYTICS" title="Motor analítico" action={<Badge kind="ok">EVIDENCE FIRST</Badge>}/><div className="analytics-tabs advanced-tabs"><span className="active">Estado</span><span>Concentración</span><span>Tendencia</span><span>Vintage</span><span>Migración</span><span>Stress</span><span>Drivers</span></div><div className="analytics-command"><Card><SectionHead eyebrow="ESTADO" title="Severidad actual"/><RiskRow bucket="PAR30" value={metrics.par30}/><RiskRow bucket="PAR60" value={metrics.par60}/><RiskRow bucket="PAR90" value={metrics.par90}/></Card><Card><SectionHead eyebrow="TENDENCIA" title="Qué podemos afirmar"/><div className="baseline-panel"><strong>{trend?'Comparación habilitada':'Baseline · comparación deshabilitada'}</strong><p>{trend?history.interpretation:'Sin un corte anterior real, cualquier delta sería artificial. RiskIQ no debe convertir ausencia de historia en “estabilidad”.'}</p></div></Card></div><Card><SectionHead eyebrow="DRIVERS" title="Evidencia que debe explicar el riesgo"/><Concentration segments={segments} drivers={drivers} metrics={metrics}/></Card><Card><SectionHead eyebrow="GOBERNANZA ANALÍTICA" title="Reglas de interpretación"/><div className="governance-grid"><div><b>Severidad</b><span>Describe el nivel actual por bucket.</span></div><div><b>Tendencia</b><span>Requiere cortes comparables.</span></div><div><b>Materialidad</b><span>Prioriza exposición económica.</span></div><div><b>Causalidad</b><span>No se infiere automáticamente.</span></div></div></Card></div>}

function Decisions({center,result,onRun}){const cards=center?.cards||result?.decision_cards||[];return <div className="page-content"><SectionHead eyebrow="DECISION CENTER" title="Decisiones revisables" action={<button className="secondary" onClick={onRun}>Actualizar evidencia</button>}/><div className="decision-overview advanced-overview"><div><strong>{center?.counts?.critical||0}</strong><span>Críticas</span></div><div><strong>{center?.counts?.high||0}</strong><span>Altas</span></div><div><strong>{center?.counts?.total_cards||cards.length}</strong><span>Total</span></div><div><strong>0</strong><span>Ejecutadas</span></div></div><Card className="decision-list">{cards.length?cards.map((c,i)=><div className="decision-item" key={i}><div><Badge kind={c.severity==='critical'?'critical':c.severity==='high'?'warn':'ok'}>{c.severity||'REVISAR'}</Badge><h3>{c.title||c.segment||'Revisión'}</h3><p>{c.reason||c.rationale||c.evidence||'Revisión recomendada según evidencia.'}</p></div><span>REVISIÓN HUMANA</span></div>):<div className="baseline-panel"><strong>No hay decisiones calculadas.</strong><p>Ejecuta el análisis para construir la cola de revisión.</p></div>}</Card></div>}
function Scenario({shock,setShock,sim,onRun,metrics}){return <div className="page-content"><SectionHead eyebrow="SCENARIO LAB" title="Stress y sensibilidad"/><div className="command-grid"><Card><div className="eyebrow">ESCENARIO HIPOTÉTICO</div><h2>Shock de mora</h2><p>Prueba sensibilidad sobre PAR30. El resultado es un escenario, no una predicción.</p><div className="scenario-control"><input type="range" min="0" max="100" value={shock} onChange={e=>setShock(Number(e.target.value))}/><strong>+{shock}%</strong></div><button className="primary" onClick={onRun}>Ejecutar escenario</button></Card><Card><SectionHead eyebrow="IMPACTO" title="Resultado"/><div className="scenario-values"><div><span>Actual</span><b>{pct(metrics.par30)}</b></div><div><span>Shock</span><b>+{shock}%</b></div><div><span>Estimado</span><b>{sim?.par30!=null?pct(sim.par30):'—'}</b></div></div></Card></div></div>}
function Data({file,setFile,discovery,mappings,setMappings,discover,ingest}){return <div className="page-content"><SectionHead eyebrow="DATA" title="Ingesta y calidad de datos"/><Card className="data-card"><div className="eyebrow">CSV / XLSX</div><h2>Construir una cartera analizable</h2><p>Descubre campos, valida el mapeo y normaliza antes de ejecutar el motor.</p><input type="file" accept=".csv,.xlsx,.xls" onChange={e=>setFile(e.target.files?.[0]||null)}/><div className="data-actions"><span>{file?.name||'Ningún archivo seleccionado'}</span><button className="primary" disabled={!file} onClick={discover}>Descubrir campos</button></div>{discovery&&<div className="mapping"><SectionHead eyebrow="VALIDACIÓN" title="Mapeo de campos"/><div>{mappings.map((m,i)=><div className="mapping-row" key={i}><span>{m.source}</span><b>→</b><input value={m.target||''} onChange={e=>setMappings(ms=>ms.map((x,j)=>j===i?{...x,target:e.target.value}:x))}/>{m.required&&<Badge kind="warn">Requerido</Badge>}</div>)}</div><button className="primary wide" onClick={ingest}>Cargar y analizar</button></div>}</Card></div>}
function Datasets({items,active,onSelect}){return <div className="page-content"><SectionHead eyebrow="DATASETS" title="Cortes y fuentes"/><Card className="dataset-list">{items.length?items.map((d,i)=><button key={d.dataset_id||i} className={active?.dataset_id===d.dataset_id?'dataset-row active':'dataset-row'} onClick={()=>onSelect(d)}><div><b>{d.source_name||d.name||`Dataset ${i+1}`}</b><small>{d.dataset_id}</small></div><span>{active?.dataset_id===d.dataset_id?'Activo':'Seleccionar'}</span></button>):<div className="muted">No hay datasets registrados.</div>}</Card></div>}
function Copilot({question,setQuestion,answer,onAsk,loading}){return <div className="page-content"><SectionHead eyebrow="RISK COPILOT" title="Analista sobre evidencia"/><Card className="copilot-card"><div className="eyebrow">GROUNDED IN CALCULATED EVIDENCE</div><h2>Pregunta por la cartera</h2><p>El Copilot debe explicar evidencia calculada: dónde está el riesgo, qué lo explica, qué cambió y qué revisar.</p><div className="copilot-input"><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>e.key==='Enter'&&onAsk()} placeholder="Ej.: ¿dónde se concentra el problema?"/><button className="primary" onClick={onAsk} disabled={loading}>{loading?'Consultando…':'Preguntar'}</button></div>{answer&&<div className="answer"><div className="eyebrow">RESPUESTA</div><p>{answer.answer||answer.message||JSON.stringify(answer)}</p></div>}</Card></div>}
