import {useState} from 'react'
import {CheckCircle2,ChevronRight,Database,Eye,FileSpreadsheet,Loader2,Upload,X} from 'lucide-react'
import {discoverFile,ingestFile} from './api'
import DataExplorer from './DataExplorer'

const activeDatasetId=()=>{try{return JSON.parse(localStorage.getItem('riskiq.activeDataset')||'null')?.dataset_id||''}catch{return ''}}

export default function DataUpload(){
 const [open,setOpen]=useState(false),[explorerOpen,setExplorerOpen]=useState(false),[file,setFile]=useState(null),[discovery,setDiscovery]=useState(null),[mappings,setMappings]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false)
 const [appendMode,setAppendMode]=useState(Boolean(activeDatasetId()))
 const choose=e=>{setFile(e.target.files?.[0]||null);setDiscovery(null);setMappings([]);setError('');setDone(false)}
 const openUpload=()=>{setAppendMode(Boolean(activeDatasetId()));setOpen(true)}
 const openExplorer=()=>{if(activeDatasetId())setExplorerOpen(true)}
 const discover=async()=>{if(!file)return;setLoading(true);setError('');try{const r=await discoverFile(file);setDiscovery(r);setMappings((r.mapping_suggestions||[]).map(x=>({source:x.source,target:x.target,required:x.required})))}catch(e){setError(e.message||'No se pudo leer el archivo.')}finally{setLoading(false)}}
 const ingest=async()=>{if(!file||!mappings.length)return;setLoading(true);setError('');try{const datasetId=appendMode?activeDatasetId():'';await ingestFile(file,mappings,datasetId);setDone(true);setTimeout(()=>window.location.reload(),700)}catch(e){setError(e.message||'No se pudo procesar la cartera.')}finally{setLoading(false)}}
 return <>
  <div className="fixed right-5 top-20 z-40 flex gap-2">
   {activeDatasetId()&&<button type="button" onClick={openExplorer} className="inline-flex h-10 items-center gap-2 rounded-md border border-slate-300 bg-white px-3 text-sm font-semibold text-slate-800 shadow-sm transition hover:bg-slate-50" aria-label="Explorar datos"><Eye size={16} strokeWidth={1.7}/> Ver datos</button>}
   <button type="button" onClick={openUpload} className="inline-flex h-10 items-center gap-2 rounded-md border border-slate-300 bg-white px-3 text-sm font-semibold text-slate-800 shadow-sm transition hover:bg-slate-50" aria-label="Cargar cartera"><Upload size={16} strokeWidth={1.7}/> {appendMode?'Actualizar cartera':'Cargar cartera'}</button>
  </div>
  {explorerOpen&&<div className="fixed inset-0 z-[55] overflow-auto bg-slate-950/30 p-4 pt-20" role="dialog" aria-modal="true" aria-label="Explorador de datos"><div className="mx-auto max-w-[1500px] rounded-xl border border-slate-200 bg-slate-50 shadow-2xl"><div className="sticky top-0 z-10 flex items-center justify-between border-b border-slate-200 bg-white px-5 py-3"><div><div className="text-xs font-semibold uppercase tracking-wider text-slate-500">DATA FOUNDATION</div><div className="text-sm font-semibold text-slate-900">Explorador de datos · cartera activa</div></div><button onClick={()=>setExplorerOpen(false)} className="rounded-md p-2 text-slate-400 hover:bg-slate-100 hover:text-slate-700"><X size={18}/></button></div><div className="p-4"><DataExplorer datasetId={activeDatasetId()}/></div></div></div>}
  {open&&<div className="fixed inset-0 z-[60] flex items-start justify-center bg-slate-950/30 p-4 pt-24" role="dialog" aria-modal="true" aria-label="Cargar cartera">
   <div className="w-full max-w-3xl overflow-hidden rounded-xl border border-slate-200 bg-white shadow-2xl">
    <div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-slate-500"><Database size={14}/> Data ingestion</div><h2 className="mt-1 text-lg font-semibold text-slate-900">{appendMode?'Agregar snapshot a la cartera':'Cargar cartera de créditos'}</h2><p className="mt-0.5 text-sm text-slate-500">{appendMode?'Sube el corte del mes. RiskIQ lo relacionará con los snapshots anteriores mediante la identidad del crédito.':'CSV o Excel · descubrir campos · revisar mapeo · crear cartera.'}</p></div><button type="button" onClick={()=>setOpen(false)} className="rounded-md p-2 text-slate-400 hover:bg-slate-100 hover:text-slate-700" aria-label="Cerrar"><X size={18}/></button></div>
    <div className="space-y-5 p-5">
     {appendMode&&<div className="rounded-lg border border-blue-200 bg-blue-50/60 px-4 py-3 text-sm text-blue-800"><strong>Modo histórico activo.</strong> Esta carga conserva la misma cartera y agrega las nuevas observaciones. No reemplaza los meses anteriores.</div>}
     <div className="rounded-lg border border-dashed border-slate-300 bg-slate-50 p-6"><label className="flex cursor-pointer flex-col items-center justify-center gap-2 text-center"><FileSpreadsheet size={28} className="text-slate-500"/><span className="text-sm font-semibold text-slate-800">Selecciona CSV / XLSX</span><span className="text-xs text-slate-500">Corte mensual, snapshot o histórico completo</span><input type="file" accept=".csv,.xlsx,.xls" onChange={choose} className="sr-only"/></label>{file&&<div className="mt-4 flex items-center justify-between rounded-md border border-slate-200 bg-white px-3 py-2"><span className="truncate text-sm font-medium text-slate-700">{file.name}</span><button type="button" onClick={()=>{setFile(null);setDiscovery(null);setMappings([])}} className="text-xs text-slate-500 hover:text-slate-900">Cambiar</button></div>}</div>
     <div className="flex flex-wrap items-center gap-2"><button type="button" onClick={discover} disabled={!file||loading} className="inline-flex h-9 items-center gap-2 rounded-md bg-slate-900 px-3 text-sm font-medium text-white hover:bg-slate-800 disabled:opacity-50">{loading?<Loader2 size={15} className="animate-spin"/>:<ChevronRight size={15}/>} Detectar campos</button>{discovery&&<span className="text-xs text-slate-500">Campos detectados: {discovery.columns?.length||discovery.headers?.length||mappings.length}</span>}</div>
     {discovery&&<div className="rounded-lg border border-slate-200"><div className="border-b border-slate-200 px-4 py-3"><div className="text-xs font-semibold uppercase tracking-wider text-slate-500">Mapeo universal</div><div className="text-sm text-slate-600">Confirma qué columna de origen representa cada campo RiskIQ. Las columnas adicionales se conservan para Data Explorer y segmentación.</div></div><div className="max-h-72 overflow-auto">{mappings.map((m,i)=><div className="grid grid-cols-[1fr_auto_1fr_auto] items-center gap-3 border-b border-slate-100 px-4 py-2.5 last:border-0" key={`${m.source}-${i}`}><span className="truncate text-sm text-slate-700">{m.source||'—'}</span><span className="text-slate-400">→</span><input value={m.target||''} onChange={e=>setMappings(ms=>ms.map((x,j)=>j===i?{...x,target:e.target.value}:x))} className="h-8 rounded-md border border-slate-200 px-2 text-sm text-slate-800 outline-none focus:border-slate-400"/><span>{m.required?<span className="rounded-full bg-amber-50 px-2 py-1 text-[11px] font-medium text-amber-700">requerido</span>:null}</span></div>)}</div></div>}
     {error&&<div className="rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">{error}</div>}
     {done&&<div className="flex items-center gap-2 rounded-md border border-emerald-200 bg-emerald-50 px-3 py-2 text-sm text-emerald-700"><CheckCircle2 size={16}/> {appendMode?'Snapshot agregado a la cartera.':'Cartera creada.'} Actualizando RiskIQ…</div>}
     <div className="flex justify-end gap-2 border-t border-slate-200 pt-4"><button type="button" onClick={()=>setOpen(false)} className="h-9 rounded-md border border-slate-200 bg-white px-3 py-2 text-sm font-medium text-slate-700">Cancelar</button><button type="button" onClick={ingest} disabled={!file||!mappings.length||loading||done} className="h-9 rounded-md bg-slate-900 px-4 py-2 text-sm font-semibold text-white hover:bg-slate-800 disabled:opacity-50">{loading?'Procesando…':appendMode?'Agregar snapshot y analizar':'Crear cartera y analizar'}</button></div>
    </div>
   </div>
  </div>}
 </>
}
