import {useEffect,useMemo,useState} from 'react'
import {getDataset,getDatasetRecords,discoverDatasetData,assessDatasetQuality,getCanonicalSchema,getDatasetMapping,saveDatasetMapping} from './api'
import SegmentStudio from './SegmentStudio'
import './data-foundation.css'

const label={critical:'BLOQUEA',high:'ALTO',medium:'MEDIO',warning:'ADVERTENCIA'}
const friendly={loan_id:'Crédito / cuenta',customer_id:'Cliente',outstanding_principal:'Saldo de capital',dpd:'Días de mora',origination_date:'Fecha de originación',snapshot_date:'Fecha de corte',segment:'Segmento'}

function localDiscovery(rows,existing){
 const columns=[...new Set(rows.flatMap(row=>Object.keys(row||{})))].map(name=>({name,type:'text',completeness:rows.length?rows.filter(row=>row?.[name]!==null&&row?.[name]!=='').length/rows.length:0,sample:rows.slice(0,3).map(row=>row?.[name]).filter(v=>v!==null&&v!=='')}))
 const aliases={loan_id:['loan_id','credito','crédito','credit_id'],customer_id:['customer_id','cliente','client_id'],snapshot_date:['snapshot_date','snapshot_month','fecha_corte','fecha corte','as_of_date'],outstanding_principal:['outstanding_principal','saldo','saldo_capital','saldo_pendiente','balance'],dpd:['dpd','dias_mora','días_mora','days_past_due','mora'],origination_date:['origination_date','fecha_desembolso','fecha_otorgamiento'],segment:['segment','segmento','categoria','categoría']}
 const suggestions=[]
 columns.forEach(column=>{const normalized=String(column.name).trim().toLowerCase();for(const [target,names] of Object.entries(aliases)){if(names.some(alias=>normalized===alias||normalized.replace(/[^a-z0-9áéíóúüñ]/g,'_')===alias)){suggestions.push({source:column.name,target,confidence:1,matched_alias:column.name,required:false});break}}})
 const mappings=existing?.mapping?.mappings?.length?existing.mapping.mappings:suggestions
 return {version:'local-fallback-v1',row_count:rows.length,column_count:columns.length,columns,mapping_suggestions:mappings,mapped_target_count:new Set(mappings.map(m=>m.target)).size,warnings:['Perfil reconstruido localmente a partir de las columnas recibidas.']}
}

export default function DataFoundation({datasetId='',onContinue}){
 const [records,setRecords]=useState([]),[discovery,setDiscovery]=useState(null),[quality,setQuality]=useState(null),[schema,setSchema]=useState(null),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[saved,setSaved]=useState(false),[error,setError]=useState(''),[tab,setTab]=useState('quality')
 useEffect(()=>{if(datasetId)load(datasetId)},[datasetId])
 async function load(id){setLoading(true);setSaved(false);setError('');try{
   const raw=await getDatasetRecords(id);const data=Array.isArray(raw)?raw:(raw?.records||raw?.data||[]);setRecords(data)
   const [existing,meta,s]=await Promise.all([getDatasetMapping(id).catch(()=>null),getDataset(id).catch(()=>null),getCanonicalSchema().catch(()=>null)])
   let d;try{d=await discoverDatasetData(data)}catch{d=localDiscovery(data,existing)}
   if(!d?.columns?.length&&data.length)d=localDiscovery(data,existing)
   if(existing?.mapping?.mappings?.length)d.mapping_suggestions=existing.mapping.mappings
   setDiscovery(d);setSchema(s)
   try{const q=await assessDatasetQuality(data,d.mapping_suggestions||[]);setQuality(q)}catch{
     const persistedScore=Number(meta?.quality_score);setQuality({quality_score:Number.isFinite(persistedScore)?persistedScore:0,status:meta?.quality_status||'warning',row_count:data.length,column_count:d.column_count||0,issue_count:meta?.quality_issue_count||0,issues:meta?.quality_issues||[],row_issues:[],analysis_impacts:[],checks:{completeness:0,validity:0},limitations:['La evaluación detallada de calidad no respondió; se muestra el último estado persistido del dataset.']})
   }
 }catch(e){setError(e.message)}finally{setLoading(false)}}
 async function confirmMapping(){if(!datasetId||!mappings.length)return;setSaving(true);setError('');try{await saveDatasetMapping(datasetId,mappings);setSaved(true)}catch(e){setError(e.message)}finally{setSaving(false)}}
 const columns=useMemo(()=>discovery?.columns||[],[discovery]);const mappings=discovery?.mapping_suggestions||[];const readyModels=(quality?.analysis_impacts||[]).filter(x=>x.ready).length;const modelTotal=(quality?.analysis_impacts||[]).length;const canContinue=Boolean(quality&&(quality.status==='passed'||quality.status==='warning'))
 if(!datasetId)return <div className="df-empty"><strong>Selecciona una cartera para preparar sus datos.</strong><span>RiskIQ validará la estructura antes de ejecutar análisis.</span></div>
 return <section className="df-panel">
  <div className="df-head"><div><span>DATA FOUNDATION</span><h2>Preparación y confianza de datos</h2><p>RiskIQ separa el dato original del modelo financiero canónico antes de calcular riesgo.</p></div><div className={`df-status ${loading?'loading':quality?.status||'blocked'}`}>{loading?'VALIDANDO':quality?.status==='passed'?'LISTO':quality?.status==='warning'?'REVISAR':'BLOQUEADO'}</div></div>
  {error&&<div className="df-error">{error}</div>}
  <div className="df-summary"><div><span>FILAS</span><strong>{records.length.toLocaleString()}</strong></div><div><span>CAMPOS DETECTADOS</span><strong>{discovery?.column_count||0}</strong></div><div><span>CALIDAD</span><strong>{quality?.quality_score??0}<small>/100</small></strong></div><div><span>ANÁLISIS LISTOS</span><strong>{readyModels}<small>/{modelTotal||0}</small></strong></div></div>
  <div className="df-tabs"><button className={tab==='quality'?'active':''} onClick={()=>setTab('quality')}>Calidad</button><button className={tab==='mapping'?'active':''} onClick={()=>setTab('mapping')}>Mapeo universal</button><button className={tab==='rows'?'active':''} onClick={()=>setTab('rows')}>Datos y errores</button><button className={tab==='segments'?'active':''} onClick={()=>setTab('segments')}>Segmentación</button><button className={tab==='models'?'active':''} onClick={()=>setTab('models')}>Readiness</button></div>
  {tab==='quality'&&<QualityView quality={quality}/>} {tab==='mapping'&&<MappingView mappings={mappings} schema={schema} saving={saving} saved={saved} onConfirm={confirmMapping}/>} {tab==='rows'&&<RowsView records={records} issues={quality?.row_issues||[]} columns={columns}/>} {tab==='segments'&&<SegmentStudio datasetId={datasetId} columns={columns}/>} {tab==='models'&&<ReadinessView impacts={quality?.analysis_impacts||[]}/>} 
  {canContinue&&<div className="df-next-step"><div><span>NEXT STEP</span><strong>La evidencia está lista para diagnóstico</strong><p>RiskIQ conservará este corte como base y pasará al motor de diagnóstico sin modificar los datos fuente.</p></div><button type="button" onClick={onContinue}>Continuar a diagnóstico →</button></div>}
 </section>
}

function QualityView({quality}){const issues=quality?.issues||[];return <div className="df-grid"><div className="df-card"><div className="df-card-title"><span>QUALITY SCORE</span><strong>{quality?.quality_score??0}/100</strong></div><div className="df-progress"><i style={{width:`${Math.max(0,Math.min(100,Number(quality?.quality_score||0)))}%`}}/></div><p>La calidad mide completitud y validez del dato. No representa el riesgo financiero de la cartera.</p><div className="df-stats"><div><span>Completitud</span><b>{((quality?.checks?.completeness||0)*100).toFixed(1)}%</b></div><div><span>Validez</span><b>{((quality?.checks?.validity||0)*100).toFixed(1)}%</b></div></div></div><div className="df-card"><div className="df-card-title"><span>ISSUES</span><strong>{quality?.issue_count||0}</strong></div>{issues.length?issues.slice(0,8).map(i=><div className="df-issue" key={i.code}><span className={`sev ${i.severity}`}>{label[i.severity]||i.severity}</span><div><b>{i.code}</b><small>{i.count} ocurrencia(s)</small></div></div>):<div className="df-ok">No se detectaron incidencias en las validaciones activas.</div>}</div><div className="df-card wide"><div className="df-card-title"><span>IMPACTO ANALÍTICO</span><strong>Qué puede ejecutarse</strong></div><div className="impact-grid">{(quality?.analysis_impacts||[]).map(x=><div className={`impact ${x.ready?'ready':'blocked'}`} key={x.model}><div><b>{x.model}</b><span>{x.label}</span></div><strong>{x.ready?'LISTO':'LIMITADO'}</strong>{!x.ready&&<small>Falta: {(x.missing_fields||[]).map(f=>friendly[f]||f).join(', ')}</small>}</div>)}</div></div></div>}
function MappingView({mappings,schema,saving,saved,onConfirm}){return <div className="df-card"><div className="df-card-title"><div><span>UNIVERSAL FINANCIAL MODEL</span><strong>{mappings.length} mapeos detectados</strong></div><button className="df-confirm" onClick={onConfirm} disabled={!mappings.length||saving}>{saving?'GUARDANDO…':saved?'MAPEO CONFIRMADO':'CONFIRMAR MAPEO'}</button></div><p>Los nombres de la empresa pueden cambiar; RiskIQ conserva la semántica financiera confirmada para futuras actualizaciones.</p><div className="mapping-table"><div className="mapping-row header"><span>FUENTE</span><span>RISKIQ</span><span>CONFIANZA</span></div>{mappings.map(m=><div className="mapping-row" key={`${m.source}-${m.target}`}><span>{m.source}</span><b>{schema?.fields?.find(f=>f.id===m.target)?.label||friendly[m.target]||m.target}</b><span>{Math.round(Number(m.confidence||0)*100)}%</span></div>)}</div></div>}
function RowsView({records,issues,columns}){const byRow=new Map();issues.forEach(i=>{const current=byRow.get(i.row)||[];current.push(i);byRow.set(i.row,current)});const issueFor=row=>byRow.get(row)||[];return <div className="df-card wide"><div className="df-card-title"><span>SOURCE DATA</span><strong>{records.length.toLocaleString()} registros · {columns.length} columnas</strong></div><p>Vista completa del dato recibido. Los errores se muestran sobre el registro que los origina para permitir corrección en la base fuente.</p><div className="source-table"><table><thead><tr><th>#</th>{columns.map(c=><th key={c.name||c}>{c.name||c}</th>)}</tr></thead><tbody>{records.slice(0,100).map((row,index)=><tr className={issueFor(index).length?'has-issue':''} key={index}><td>{index+1}</td>{columns.map(c=>{const name=c.name||c;const cell=issueFor(index).find(x=>x.field===name);return <td key={name} className={cell?'cell-issue':''} title={cell?.message||''}>{String(row[name]??'—')}</td>})}</tr>)}</tbody></table></div><small className="table-note">{records.length>100?'Mostrando los primeros 100 registros. ':''}{issues.length>500?'Se muestran hasta 500 incidencias para proteger el rendimiento.':''}</small></div>}
function ReadinessView({impacts}){return <div className="readiness-list">{impacts.map(x=><div className={`readiness ${x.ready?'ready':'blocked'}`} key={x.model}><div><span>{x.ready?'✓':'!'}</span><div><b>{x.model}</b><small>{x.label}</small></div></div><strong>{x.ready?'READY':'NOT READY'}</strong>{!x.ready&&<p>Faltan campos: {(x.missing_fields||[]).map(f=>friendly[f]||f).join(', ')}</p>}</div>)}</div>}
