import {useEffect,useMemo,useState} from 'react'
import {getDatasetRecords,discoverDatasetData,assessDatasetQuality,getCanonicalSchema,getMappingReadiness} from './api'
import './data-foundation.css'

const label={critical:'BLOQUEA',high:'ALTO',medium:'MEDIO',warning:'ADVERTENCIA'}
const friendly={loan_id:'Crédito / cuenta',customer_id:'Cliente',outstanding_principal:'Saldo de capital',dpd:'Días de mora',origination_date:'Fecha de originación',snapshot_date:'Fecha de corte',segment:'Segmento'}

export default function DataFoundation({datasetId=''}){
 const [records,setRecords]=useState([]),[discovery,setDiscovery]=useState(null),[quality,setQuality]=useState(null),[schema,setSchema]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[tab,setTab]=useState('quality')
 useEffect(()=>{if(!datasetId)return;load(datasetId)},[datasetId])
 async function load(id){setLoading(true);setError('');try{const rows=await getDatasetRecords(id);const data=Array.isArray(rows)?rows:(rows?.records||rows?.data||[]);setRecords(data);const [d,q,s]=await Promise.all([discoverDatasetData(data),assessDatasetQuality(data),getCanonicalSchema()]);setDiscovery(d);setQuality(q);setSchema(s)}catch(e){setError(e.message)}finally{setLoading(false)}}
 const columns=useMemo(()=>discovery?.columns||[],[discovery])
 const mappings=discovery?.mapping_suggestions||[]
 const readyModels=(quality?.analysis_impacts||[]).filter(x=>x.ready).length
 const modelTotal=(quality?.analysis_impacts||[]).length
 if(!datasetId)return <div className="df-empty"><strong>Selecciona una cartera para preparar sus datos.</strong><span>RiskIQ validará la estructura antes de ejecutar análisis.</span></div>
 return <section className="df-panel">
  <div className="df-head"><div><span>DATA FOUNDATION</span><h2>Preparación y confianza de datos</h2><p>RiskIQ separa el dato original del modelo financiero canónico antes de calcular riesgo.</p></div><div className={`df-status ${quality?.status||'loading'}`}>{loading?'VALIDANDO':quality?.status==='passed'?'LISTO':quality?.status==='warning'?'REVISAR':'BLOQUEADO'}</div></div>
  {error&&<div className="df-error">{error}</div>}
  <div className="df-summary"><div><span>FILAS</span><strong>{records.length.toLocaleString()}</strong></div><div><span>CAMPOS DETECTADOS</span><strong>{discovery?.column_count||0}</strong></div><div><span>CALIDAD</span><strong>{quality?.quality_score??0}<small>/100</small></strong></div><div><span>ANÁLISIS LISTOS</span><strong>{readyModels}<small>/{modelTotal||0}</small></strong></div></div>
  <div className="df-tabs"><button className={tab==='quality'?'active':''} onClick={()=>setTab('quality')}>Calidad</button><button className={tab==='mapping'?'active':''} onClick={()=>setTab('mapping')}>Mapeo universal</button><button className={tab==='rows'?'active':''} onClick={()=>setTab('rows')}>Datos y errores</button><button className={tab==='models'?'active':''} onClick={()=>setTab('models')}>Readiness</button></div>
  {tab==='quality'&&<QualityView quality={quality}/>} {tab==='mapping'&&<MappingView mappings={mappings} schema={schema}/>} {tab==='rows'&&<RowsView records={records} issues={quality?.row_issues||[]} columns={columns}/>} {tab==='models'&&<ReadinessView impacts={quality?.analysis_impacts||[]}/>} 
 </section>
}

function QualityView({quality}){const issues=quality?.issues||[];return <div className="df-grid"><div className="df-card"><div className="df-card-title"><span>QUALITY SCORE</span><strong>{quality?.quality_score??0}/100</strong></div><div className="df-progress"><i style={{width:`${Math.max(0,Math.min(100,Number(quality?.quality_score||0)))}%`}}/></div><p>La calidad mide completitud y validez del dato. No representa el riesgo financiero de la cartera.</p><div className="df-stats"><div><span>Completitud</span><b>{((quality?.checks?.completeness||0)*100).toFixed(1)}%</b></div><div><span>Validez</span><b>{((quality?.checks?.validity||0)*100).toFixed(1)}%</b></div></div></div><div className="df-card"><div className="df-card-title"><span>ISSUES</span><strong>{quality?.issue_count||0}</strong></div>{issues.length?issues.slice(0,8).map(i=><div className="df-issue" key={i.code}><span className={`sev ${i.severity}`}>{label[i.severity]||i.severity}</span><div><b>{i.code}</b><small>{i.count} ocurrencia(s)</small></div></div>):<div className="df-ok">No se detectaron incidencias en las validaciones activas.</div>}</div><div className="df-card wide"><div className="df-card-title"><span>IMPACTO ANALÍTICO</span><strong>Qué puede ejecutarse</strong></div><div className="impact-grid">{(quality?.analysis_impacts||[]).map(x=><div className={`impact ${x.ready?'ready':'blocked'}`} key={x.model}><div><b>{x.model}</b><span>{x.label}</span></div><strong>{x.ready?'LISTO':'LIMITADO'}</strong>{!x.ready&&<small>Falta: {(x.missing_fields||[]).map(f=>friendly[f]||f).join(', ')}</small>}</div>)}</div></div></div>}
function MappingView({mappings,schema}){return <div className="df-card"><div className="df-card-title"><span>UNIVERSAL FINANCIAL MODEL</span><strong>{mappings.length} mapeos detectados</strong></div><p>Los nombres de la empresa pueden cambiar; RiskIQ trabaja con una semántica financiera estable.</p><div className="mapping-table"><div className="mapping-row header"><span>FUENTE</span><span>RISKIQ</span><span>CONFIANZA</span></div>{mappings.map(m=><div className="mapping-row" key={`${m.source}-${m.target}`}><span>{m.source}</span><b>{schema?.fields?.find(f=>f.id===m.target)?.label||friendly[m.target]||m.target}</b><span>{Math.round(Number(m.confidence||0)*100)}%</span></div>)}</div></div>}
function RowsView({records,issues,columns}){const byRow=new Map(issues.map(i=>[i.row,(byRowGet(byRow,i.row)||[]).concat(i)]));function issueFor(row){return byRow.get(row)||[]}return <div className="df-card wide"><div className="df-card-title"><span>SOURCE DATA</span><strong>{records.length.toLocaleString()} registros</strong></div><p>Los errores se muestran sobre el registro que los origina para permitir corrección en la base fuente.</p><div className="source-table"><table><thead><tr><th>#</th>{columns.slice(0,8).map(c=><th key={c.name||c}>{c.name||c}</th>)}</tr></thead><tbody>{records.slice(0,100).map((row,index)=><tr className={issueFor(index).length?'has-issue':''} key={index}><td>{index+1}</td>{columns.slice(0,8).map(c=>{const name=c.name||c;const cell=issueFor(index).find(x=>x.field===name);return <td key={name} className={cell?'cell-issue':''} title={cell?.message||''}>{String(row[name]??'—')}</td>})}</tr>)}</tbody></table></div><small className="table-note">{records.length>100?'Mostrando los primeros 100 registros. ':''}{issues.length>500?'Se muestran hasta 500 incidencias para proteger el rendimiento.':''}</small></div>}
function byRowGet(map,index){return map.get(index)||[]}
function ReadinessView({impacts}){return <div className="readiness-list">{impacts.map(x=><div className={`readiness ${x.ready?'ready':'blocked'}`} key={x.model}><div><span>{x.ready?'✓':'!'}</span><div><b>{x.model}</b><small>{x.label}</small></div></div><strong>{x.ready?'READY':'NOT READY'}</strong>{!x.ready&&<p>Faltan campos: {(x.missing_fields||[]).map(f=>friendly[f]||f).join(', ')}</p>}</div>)}</div>}
