import React,{useMemo,useState} from 'react'
import {compileDecisionRule,evaluateDecisionFormulas,evaluateDecisionRule,normalizeDecisionRows,saveDecisionRule} from './api'
const FIELDS=[['par7','PAR7'],['par30','PAR30'],['par60','PAR60'],['par90','PAR90'],['outstanding_balance','Exposición'],['priority_score','Priority score'],['segment','Segmento'],['product','Producto'],['trend','Tendencia']]
const OPS=[['gt','mayor que'],['gte','mayor o igual que'],['lt','menor que'],['lte','menor o igual que'],['eq','igual a'],['neq','distinto de']]
const blank=()=>({field:'par30',operator:'gt',value:'0.10'})
const starter=`par30 = to_number(par30)\nexposure = to_number(outstanding_balance)\nreturn {\n  "matched": par30 >= 0.10 and exposure > 50000,\n  "risk_level": "HIGH_RISK" if par30 >= 0.10 else "WATCH",\n  "normalized_segment": upper(coalesce(segment, "UNKNOWN"))\n}`
const normalizer=`return {\n  "customer_id": to_text(customer_id),\n  "dpd": to_number(dpd),\n  "outstanding_principal": to_number(outstanding_principal),\n  "segment": upper(coalesce(segment, "UNKNOWN"))\n}`
const formulaStarter={"par30_ratio":"to_number(par30)","exposure":"to_number(outstanding_balance)","risk_score":"round(par30_ratio * 700 + min(exposure / 100000, 1) * 300, 2)","risk_band":"CRITICAL" if False else "WATCH"}
export default function DecisionEngine({current={},onApply}){
 const [name,setName]=useState('Early Delinquency'),[mode,setMode]=useState('visual'),[logic,setLogic]=useState('AND'),[conditions,setConditions]=useState([blank()]),[outcome,setOutcome]=useState('HIGH_RISK'),[priority,setPriority]=useState('1'),[action,setAction]=useState('Crear revisión humana'),[code,setCode]=useState(starter),[normalizer,setNormalizer]=useState(normalizer),[formulas,setFormulas]=useState(JSON.stringify(formulaStarter,null,2)),[tab,setTab]=useState('decision'),[status,setStatus]=useState('Listo para probar'),[result,setResult]=useState(null),[busy,setBusy]=useState(false)
 const formulaObject=useMemo(()=>{try{return JSON.parse(formulas)}catch{return null}},[formulas])
 const preview=useMemo(()=>({id:'POL-'+name.toUpperCase().replace(/[^A-Z0-9]+/g,'-').slice(0,30),version:1,name,execution_mode:mode,logic,conditions,formulas:formulaObject||{},code,actions:[{type:'recommend',parameters:{outcome,priority:Number(priority)||0,action}}],mode:'suggested',enabled:true}),[name,mode,logic,conditions,formulas,formulaObject,code,outcome,priority,action])
 const update=(i,p)=>setConditions(xs=>xs.map((x,j)=>j===i?{...x,...p}:x))
 const run=async()=>{setBusy(true);try{if(tab==='normalize'){const r=await normalizeDecisionRows(Object.keys(current).length?[current]:[{customer_id:'demo',dpd:'45',outstanding_principal:'125000',segment:'premium'}],normalizer);setResult(r.rows);setStatus('Normalización ejecutada · sandbox')}else if(mode==='formula'){if(!formulaObject)throw new Error('El JSON de fórmulas no es válido');const r=await evaluateDecisionFormulas(formulaObject,current);setResult(r);setStatus('Fórmulas calculadas · sandbox')}else{const r=await evaluateDecisionRule(preview,current);setResult(r.result);setStatus('Simulación ejecutada · sin acciones externas')}}catch(e){setStatus('Error: '+e.message)}finally{setBusy(false)}}
 const validate=async()=>{setBusy(true);try{await compileDecisionRule(preview);setStatus('Lógica válida · contrato RiskIQ Decision Engine')}catch(e){setStatus('Error: '+e.message)}finally{setBusy(false)}}
 const save=async()=>{setBusy(true);try{const r=await saveDecisionRule(preview);setStatus('Versión guardada · '+(r.rule?.version?'v'+r.rule.version:'lista para gobernanza'));onApply?.(r.rule)}catch(e){setStatus('Error: '+e.message)}finally{setBusy(false)}}
 const tabs=[['visual','Visual','Negocio'],['formula','Fórmulas','Analistas'],['code','Risk DSL','Avanzado']]
 return <section className="decision-engine de-v3" aria-label="Decision Engine"><header className="de-v3__hero"><div><span className="section-eyebrow">DECISION ENGINE · V4</span><h2>Policy & Logic Studio</h2><p>De datos heterogéneos a variables, fórmulas, reglas, decisiones y evidencia trazable.</p></div><span className="de-v3__badge">SANDBOXED · AUDITABLE</span></header>
 <div className="de-v3__tabs">{tabs.map(([v,l,s])=><button key={v} className={mode===v&&tab==='decision'?'active':''} onClick={()=>{setMode(v);setTab('decision')}}>{l}<small>{s}</small></button>)}<button className={tab==='normalize'?'active':''} onClick={()=>setTab('normalize')}>Normalize Data<small>Data engineering</small></button></div>
 <div className="de-v3__layout"><main><label>Nombre de política<input value={name} onChange={e=>setName(e.target.value)}/></label>{tab==='normalize'?<div className="de-code"><div className="de-code__head"><strong>DATA TRANSFORM</strong><span>Normalización controlada · fila por fila</span></div><textarea spellCheck="false" value={normalizer} onChange={e=>setNormalizer(e.target.value)}/><div className="de-code__hint">Mapea columnas, limpia tipos, normaliza texto y devuelve el contrato canónico. Sin imports, red ni archivos.</div></div>:mode==='code'?<div className="de-code"><div className="de-code__head"><strong>RISK DSL</strong><span>Python-like · sandboxed · deterministic</span></div><textarea spellCheck="false" value={code} onChange={e=>setCode(e.target.value)}/><div className="de-code__hint">Asignaciones · cálculos · IF · return · funciones aprobadas. Úsalo cuando la lógica exceda una regla parametrizada.</div></div>:mode==='formula'?<div className="de-code de-formula"><div className="de-code__head"><strong>DERIVED FACTS / SCORECARD</strong><span>JSON de variables → expresiones seguras</span></div><textarea spellCheck="false" value={formulas} onChange={e=>setFormulas(e.target.value)}/><div className="de-code__hint">Cada clave crea una variable reutilizable por las siguientes fórmulas. Ej.: utilization = exposure / credit_limit · risk_score = weighted score.</div></div>:<div className="builder-block"><div className="builder-block__title"><strong>WHEN</strong><span>{conditions.length} condición{conditions.length!==1?'es':''}</span></div>{conditions.map((c,i)=><React.Fragment key={i}>{i>0&&<div className="logic-row"><select value={logic} onChange={e=>setLogic(e.target.value)}><option>AND</option><option>OR</option></select></div>}<div className="condition-row"><select value={c.field} onChange={e=>update(i,{field:e.target.value})}>{FIELDS.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select><select value={c.operator} onChange={e=>update(i,{operator:e.target.value})}>{OPS.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select><input value={c.value} onChange={e=>update(i,{value:e.target.value})}/>{conditions.length>1&&<button className="button button--ghost" onClick={()=>setConditions(xs=>xs.filter((_,j)=>j!==i))}>Quitar</button>}</div></React.Fragment>)}<button className="button button--secondary" onClick={()=>setConditions(xs=>[...xs,blank()])}>+ Agregar condición</button></div>}
 {tab!=='normalize'&&<div className="builder-block"><div className="builder-block__title"><strong>THEN</strong><span>Resultado y acción</span></div><div className="then-grid"><label>Nivel<select value={outcome} onChange={e=>setOutcome(e.target.value)}><option>LOW_RISK</option><option>WATCH</option><option>HIGH_RISK</option><option>CRITICAL</option><option>REVIEW</option></select></label><label>Prioridad<input type="number" min="1" max="5" value={priority} onChange={e=>setPriority(e.target.value)}/></label><label>Acción<input value={action} onChange={e=>setAction(e.target.value)}/></label></div></div>}
 <div className="engine-actions"><button className="button button--primary" disabled={busy} onClick={run}>{busy?'Ejecutando…':'Probar en sandbox'}</button>{tab!=='normalize'&&<><button className="button button--secondary" disabled={busy} onClick={validate}>Validar / compilar</button><button className="button button--secondary" disabled={busy} onClick={save}>Guardar versión</button></>}<span className="save-confirm">{status}</span></div></main>
 <aside className="decision-engine__preview"><span className="section-eyebrow">EXECUTION PLAN</span><h3>{tab==='normalize'?'Normalization Pipeline':name}</h3><div className="de-v3__pipeline"><span>DATA</span><i>→</i><span>NORMALIZE</span><i>→</i><span>FACTS</span><i>→</i><span>FORMULAS</span><i>→</i><span>LOGIC</span><i>→</i><span>DECISION</span></div>{result&&<pre className="de-v3__result">{JSON.stringify(result,null,2)}</pre>}<div className="evidence-box"><strong>Runtime</strong><p>{tab==='normalize'?'Transformación de datos':mode==='code'?'Risk DSL':mode==='formula'?'Fórmulas y scorecards':'Reglas visuales'} · sandboxed</p></div><div className="evidence-box"><strong>Gobernanza</strong><p>Validación, simulación, versionado, trazabilidad y separación entre decisión y ejecución.</p></div></aside></div></section>
}