import React,{useMemo,useState} from 'react'
import {compileDecisionRule,evaluateDecisionScorecard,normalizeDecisionRows,runDecisionPipeline,saveDecisionRule} from './api'

const STAGES=[['data','01','Data','Input & contracts'],['normalize','02','Normalize','Canonical model'],['facts','03','Variables','Derived facts'],['scorecard','04','Scorecard','Weighted risk'],['rules','05','Rules','Policy logic'],['code','06','Risk DSL','Advanced logic'],['decision','07','Decision','Outcome'],['simulate','08','Simulate','Test cases'],['governance','09','Governance','Version & audit']]
const FIELDS=[['par7','PAR7'],['par30','PAR30'],['par60','PAR60'],['par90','PAR90'],['outstanding_balance','Exposición'],['priority_score','Priority score'],['segment','Segmento'],['product','Producto'],['trend','Tendencia'],['risk_score','Risk score']]
const OPS=[['gt','mayor que'],['gte','mayor o igual que'],['lt','menor que'],['lte','menor o igual que'],['eq','igual a'],['neq','distinto de']]
const SAMPLE={customer_id:'C-10482',par7:0.04,par30:0.12,par60:0.07,par90:0.02,outstanding_balance:82000,segment:'premium',product:'consumer',trend:'deteriorating',credit_limit:120000}
const NORMALIZER=`return {\n  "customer_id": to_text(customer_id),\n  "par30": to_number(par30),\n  "outstanding_balance": to_number(outstanding_balance),\n  "segment": upper(coalesce(segment, "UNKNOWN")),\n  "product": upper(coalesce(product, "UNKNOWN"))\n}`
const DSL=`par30 = to_number(par30)\nexposure = to_number(outstanding_balance)\nutilization = exposure / max(to_number(credit_limit), 1)\nreturn {\n  "risk_level": "HIGH_RISK" if par30 >= 0.10 else "WATCH",\n  "material_exposure": exposure >= 50000,\n  "utilization": round(utilization, 4),\n  "segment": upper(coalesce(segment, "UNKNOWN"))\n}`
const blank=()=>({field:'par30',operator:'gte',value:'0.10'})
const scoreStarter=[{id:'par30_risk',name:'PAR30 pressure',formula:'to_number(par30) * 500',weight:1},{id:'utilization',name:'Utilization',formula:'min(to_number(outstanding_balance) / max(to_number(credit_limit), 1), 1) * 250',weight:1},{id:'trend_risk',name:'Trend deterioration',formula:'100 if trend == "deteriorating" else 0',weight:1},{id:'exposure_risk',name:'Exposure concentration',formula:'min(to_number(outstanding_balance) / 100000, 1) * 150',weight:1}]
const defaultScorecard={id:'SC-CREDIT-CONSUMER-V12',name:'Consumer Credit Risk v12',items:scoreStarter,bands:[{min:0,max:199,label:'LOW'},{min:200,max:399,label:'WATCH'},{min:400,max:599,label:'HIGH'},{min:600,max:10000,label:'CRITICAL'}]}

export default function DecisionEngine({current={},onApply}){
 const [stage,setStage]=useState('rules'),[policy,setPolicy]=useState('Consumer Credit Underwriting'),[version,setVersion]=useState(12),[status,setStatus]=useState('DRAFT'),[conditions,setConditions]=useState([blank()]),[logic,setLogic]=useState('AND'),[outcome,setOutcome]=useState('HIGH_RISK'),[priority,setPriority]=useState('1'),[action,setAction]=useState('Crear revisión humana'),[normalizer,setNormalizer]=useState(NORMALIZER),[dsl,setDsl]=useState(DSL),[scorecard,setScorecard]=useState(defaultScorecard),[facts,setFacts]=useState(JSON.stringify({...SAMPLE,...current},null,2)),[result,setResult]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('Workspace listo · sin acciones externas')
 const factsObject=useMemo(()=>{try{return JSON.parse(facts)}catch{return null}},[facts])
 const rule=useMemo(()=>({id:'POL-'+policy.toUpperCase().replace(/[^A-Z0-9]+/g,'-').slice(0,32),version:Number(version),name:policy,execution_mode:stage==='code'?'code':'visual',logic,conditions,code:dsl,actions:[{type:'recommend',parameters:{outcome,priority:Number(priority)||0,action}}],mode:'suggested',enabled:true}),[policy,version,logic,conditions,outcome,priority,action,dsl,stage])
 const run=async()=>{if(!factsObject){setMessage('Error · JSON de caso inválido');return}setBusy(true);try{if(stage==='normalize'){const r=await normalizeDecisionRows([factsObject],normalizer);setResult({normalized:r.rows?.[0],execution_mode:r.execution_mode});setMessage('Normalize OK · contrato canónico generado')}else if(stage==='scorecard'){const r=await evaluateDecisionScorecard(scorecard,factsObject);setResult(r.result);setMessage('Scorecard OK · score calculado y trazado')}else if(stage==='code'){const r=await runDecisionPipeline({facts:factsObject,normalization_code:normalizer,scorecard,rule:{...rule,execution_mode:'code',code:dsl}});setResult(r);setMessage('Risk DSL OK · código sandboxed y decisión simulada')}else{const r=await runDecisionPipeline({facts:factsObject,normalization_code:normalizer,scorecard,rule});setResult(r);setMessage('Pipeline OK · decisión simulada sin ejecutar acciones')}}catch(e){setMessage('Error · '+e.message)}finally{setBusy(false)}}
 const validate=async()=>{setBusy(true);try{const r=await compileDecisionRule(rule);setMessage(r.valid?'Validación OK · policy compilable':'Validación con errores');setResult(r)}catch(e){setMessage('Error · '+e.message)}finally{setBusy(false)}}
 const save=async()=>{setBusy(true);try{const r=await saveDecisionRule(rule);setStatus('TESTING');setVersion(r.rule?.version||version);setMessage('Draft guardado · listo para pruebas y gobernanza');onApply?.(r.rule)}catch(e){setMessage('Error · '+e.message)}finally{setBusy(false)}}
 const updateCondition=(i,p)=>setConditions(xs=>xs.map((x,j)=>j===i?{...x,...p}:x));const updateItem=(i,p)=>setScorecard(s=>({...s,items:s.items.map((x,j)=>j===i?{...x,...p}:x)}));const addItem=()=>setScorecard(s=>({...s,items:[...s.items,{id:'new_factor_'+(s.items.length+1),name:'New risk factor',formula:'0',weight:1}]}))
 const renderStage=()=>{
  if(stage==='data')return <div className="ri-stage-card"><div className="ri-kicker">DATA CONTRACT</div><h3>Entrada de decisión</h3><p>RiskIQ trabaja sobre un contrato de hechos, no sobre columnas aisladas. El caso actual se usa para probar toda la cadena.</p><div className="ri-stat-grid"><div><b>9</b><span>variables base</span></div><div><b>1</b><span>caso de prueba</span></div><div><b>JSON</b><span>input format</span></div></div><label>Case facts<textarea className="ri-json" value={facts} onChange={e=>setFacts(e.target.value)}/></label></div>
  if(stage==='normalize')return <div className="ri-stage-card"><div className="ri-kicker">DATA ENGINEERING</div><h3>Normalize Data</h3><p>Transforma datos heterogéneos en un modelo canónico antes de aplicar riesgo. El código se ejecuta en sandbox determinista.</p><div className="ri-editor"><div><b>Risk DSL</b><span>safe · row by row</span></div><textarea spellCheck="false" value={normalizer} onChange={e=>setNormalizer(e.target.value)}/></div></div>
  if(stage==='facts')return <div className="ri-stage-card"><div className="ri-kicker">DERIVED FACTS</div><h3>Variables calculadas</h3><p>Variables derivadas que pueden ser reutilizadas por scorecards y políticas.</p><div className="ri-fact-list">{[['par30','PAR30 ratio','0.12'],['utilization','Utilization','68.3%'],['exposure','Exposure','82,000'],['trend_risk','Trend risk','100']].map(x=><div key={x[0]}><span>{x[1]}<small>{x[0]}</small></span><strong>{x[2]}</strong></div>)}</div></div>
  if(stage==='scorecard')return <div className="ri-stage-card"><div className="ri-kicker">SCORING MODEL</div><div className="ri-title-row"><div><h3>{scorecard.name}</h3><p>Factores transparentes · fórmula + peso + contribución.</p></div><button className="ri-btn ri-btn-secondary" onClick={addItem}>+ Factor</button></div><div className="ri-score-table"><div className="ri-score-head"><span>Variable</span><span>Formula</span><span>Weight</span></div>{scorecard.items.map((x,i)=><div className="ri-score-row" key={x.id}><input value={x.name} onChange={e=>updateItem(i,{name:e.target.value})}/><input className="mono" value={x.formula} onChange={e=>updateItem(i,{formula:e.target.value})}/><input type="number" value={x.weight} step="0.1" onChange={e=>updateItem(i,{weight:e.target.value})}/></div>)}</div><div className="ri-band-row">{scorecard.bands.map(b=><span key={b.label}>{b.label} <b>{b.min}–{b.max}</b></span>)}</div></div>
  if(stage==='rules')return <div className="ri-stage-card"><div className="ri-kicker">POLICY LOGIC</div><div className="ri-title-row"><div><h3>When → Then</h3><p>Parametrización visual para negocio. El mismo policy puede combinarse con fórmulas, scorecards y Risk DSL.</p></div><span className="ri-chip">{conditions.length} condition{conditions.length!==1?'s':''}</span></div>{conditions.map((c,i)=><React.Fragment key={i}>{i>0&&<div className="ri-logic"><select value={logic} onChange={e=>setLogic(e.target.value)}><option>AND</option><option>OR</option></select></div>}<div className="ri-condition"><select value={c.field} onChange={e=>updateCondition(i,{field:e.target.value})}>{FIELDS.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select><select value={c.operator} onChange={e=>updateCondition(i,{operator:e.target.value})}>{OPS.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select><input value={c.value} onChange={e=>updateCondition(i,{value:e.target.value})}/>{conditions.length>1&&<button className="ri-icon-btn" onClick={()=>setConditions(xs=>xs.filter((_,j)=>j!==i))}>×</button>}</div></React.Fragment>)}<button className="ri-add" onClick={()=>setConditions(xs=>[...xs,blank()])}>+ Add condition</button><div className="ri-then"><div className="ri-kicker">THEN</div><label>Outcome<select value={outcome} onChange={e=>setOutcome(e.target.value)}><option>LOW_RISK</option><option>WATCH</option><option>HIGH_RISK</option><option>CRITICAL</option><option>REVIEW</option></select></label><label>Priority<input type="number" min="1" max="5" value={priority} onChange={e=>setPriority(e.target.value)}/></label><label>Action<input value={action} onChange={e=>setAction(e.target.value)}/></label></div></div>
  if(stage==='code')return <div className="ri-stage-card"><div className="ri-kicker">ADVANCED DECISION LOGIC</div><div className="ri-title-row"><div><h3>Risk DSL</h3><p>Más allá de parametrizar: crea variables, condiciones y hechos derivados con código Python-like.</p></div><span className="ri-chip">SANDBOXED · DETERMINISTIC</span></div><div className="ri-capabilities"><span>Assignments</span><span>Conditions</span><span>Derived facts</span><span>Safe functions</span><span>No I/O</span></div><div className="ri-editor"><div><b>Policy code</b><span>Python-like · controlled runtime</span></div><textarea spellCheck="false" value={dsl} onChange={e=>setDsl(e.target.value)}/></div><div className="ri-code-note">El resultado del código entra al mismo pipeline de evidencia y queda marcado como test-only.</div></div>
  if(stage==='decision'){const actual=result?.result?.decision||result?.result?.outcome||result?.decision||result?.outcome||outcome;const reasons=result?.result?.reason_codes||result?.reason_codes||['PAR30_ABOVE_THRESHOLD','EXPOSURE_MATERIAL','TREND_DETERIORATING'];return <div className="ri-stage-card"><div className="ri-kicker">DECISION CONTRACT</div><h3>Outcome & reason codes</h3><p>La decisión es un resultado explicable. Las acciones externas permanecen fuera del motor.</p><div className="ri-decision-preview"><span>RECOMMENDATION</span><strong>{actual}</strong><small>Priority {priority} · {action}</small></div><div className="ri-reasons"><b>Reason codes</b>{reasons.map((x,i)=><span key={i}>{x}</span>)}</div></div>}
  if(stage==='simulate')return <div className="ri-stage-card"><div className="ri-kicker">SCENARIO LAB</div><h3>Run a decision scenario</h3><p>Modifica los facts, ejecuta el pipeline y compara evidencia antes de publicar una versión.</p><label>Scenario facts<textarea className="ri-json" value={facts} onChange={e=>setFacts(e.target.value)}/></label></div>
  return <div className="ri-stage-card"><div className="ri-kicker">GOVERNANCE</div><h3>Policy lifecycle</h3><p>Separación clara entre editar, probar, aprobar y activar. RiskIQ no presenta un draft como producción.</p><div className="ri-lifecycle">{['DRAFT','TESTING','APPROVED','ACTIVE'].map((x,i)=><div className={x===status?'current':''} key={x}><b>{i+1}</b><span>{x}</span></div>)}</div><div className="ri-governance-grid"><div><span>Version</span><b>v{version}</b></div><div><span>Status</span><b>{status}</b></div><div><span>Runtime</span><b>Sandbox</b></div><div><span>Audit</span><b>Traceable</b></div></div></div>
 }
 const band=result?.result?.band?.label||result?.scorecard?.band?.label||result?.band?.label
 return <section className="decision-engine riskiq-decision" aria-label="RiskIQ Decision Operating System"><div className="ri-header"><div><div className="ri-kicker">DECISION CENTER / POLICY STUDIO</div><h2>Decision Operating System</h2><p>Construye decisiones desde datos hasta evidencia: <b>normalize → facts → scorecard → rules → code → decision</b>.</p></div><div className="ri-header-actions"><span className="ri-status"><i/> {status} · v{version}</span><button className="ri-btn ri-btn-secondary" disabled={busy} onClick={validate}>Validate</button><button className="ri-btn ri-btn-primary" disabled={busy} onClick={save}>Save draft</button></div></div><div className="ri-policy-bar"><div><span>POLICY</span><input value={policy} onChange={e=>setPolicy(e.target.value)}/></div><div><span>VERSION</span><b>v{version}</b></div><div><span>MODE</span><b>TEST ONLY</b></div><div><span>RUNTIME</span><b>SANDBOXED</b></div></div><div className="ri-workspace"><nav className="ri-stage-nav">{STAGES.map(([id,n,label,sub])=><button key={id} className={stage===id?'active':''} onClick={()=>setStage(id)}><b>{n}</b><span>{label}</span><small>{sub}</small></button>)}</nav><main className="ri-canvas">{renderStage()}<div className="ri-command"><button className="ri-btn ri-btn-primary" disabled={busy} onClick={run}>{busy?'Running…':stage==='simulate'?'Run full simulation':stage==='scorecard'?'Run scorecard':stage==='code'?'Run Risk DSL':'Run stage'}</button><span>{message}</span></div></main><aside className="ri-evidence"><div className="ri-kicker">EXECUTION / EVIDENCE</div><h3>{band?`Risk band · ${band}`:'Live evidence'}</h3>{result?<pre>{JSON.stringify(result,null,2)}</pre>:<><div className="ri-empty-score"><strong>—</strong><span>No run yet</span></div><p>Ejecuta el stage para poblar evidencia calculada. Todo resultado queda marcado como sandbox/test-only.</p></>}<div className="ri-evidence-card"><b>Pipeline</b><div>{STAGES.slice(0,8).map((s,i)=><span key={s[0]} className={stage===s[0]?'on':''}>{i<7?'✓':'○'} {s[2]}</span>)}</div></div><div className="ri-evidence-card"><b>Controls</b><p>✓ Deterministic runtime<br/>✓ No external actions<br/>✓ Versioned policy<br/>✓ Traceable result</p></div></aside></div></section>
}
