import {useEffect,useState} from 'react'
import {buildDiagnosis,runDataset} from './api'
import './diagnosis-brief.css'

export default function DiagnosisBrief({datasetId=''}){
 const [diagnosis,setDiagnosis]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState('')
 useEffect(()=>{if(datasetId)load(datasetId)},[datasetId])
 async function load(id){setLoading(true);setError('');try{const result=await runDataset(id);const diagnosisResult=await buildDiagnosis({analysis:result?.risk_intelligence||result?.analysis||{},data_quality:result?.risk_intelligence?.data_quality||result?.data_quality,readiness:result?.analysis_readiness||[]});setDiagnosis(diagnosisResult)}catch(e){setError(e.message)}finally{setLoading(false)}}
 if(!datasetId)return null
 const driver=diagnosis?.top_driver
 return <section className="dx-panel"><div className="dx-head"><div><span>DIAGNOSIS ENGINE</span><h2>{diagnosis?.headline||'Diagnóstico de cartera'}</h2><p>{diagnosis?.interpretation||'Construyendo una lectura basada en evidencia determinística.'}</p></div><button onClick={()=>load(datasetId)} disabled={loading}>{loading?'Actualizando…':'Actualizar diagnóstico'}</button></div>{error&&<div className="dx-error">{error}</div>}<div className="dx-grid"><div className="dx-card"><span>DRIVER PRINCIPAL</span>{driver?.available?<><strong>{driver.name}</strong><p>{((Number(driver.exposure_share)||0)*100).toFixed(1)}% de exposición · {((Number(driver.bad30_contribution)||0)*100).toFixed(1)}% de la mora 30+</p><small>PAR30 {((Number(driver.par30)||0)*100).toFixed(1)}% · prioridad {driver.priority_score}</small></>:<strong>Sin driver aislable</strong>}</div><div className="dx-card"><span>NEXT BEST ANALYSIS</span><strong>{diagnosis?.next_best_analysis?.model||'—'}</strong><p>{diagnosis?.next_best_analysis?.reason||'Ejecuta el diagnóstico para determinar el siguiente análisis.'}</p></div><div className="dx-card wide"><span>EVIDENCIA</span><div className="dx-evidence">{(diagnosis?.evidence||[]).map(item=><div key={item.metric}><b>{item.metric}</b><strong>{typeof item.value==='number'?(item.unit==='ratio'?`${(item.value*100).toFixed(1)}%`:item.value.toLocaleString()):item.value}</strong><small>{item.meaning}</small></div>)}</div></div><div className="dx-card wide"><span>LIMITACIONES Y GOBERNANZA</span><div className="dx-limitations">{(diagnosis?.limitations||[]).map((item,index)=><div key={index}><b>{item.type}</b><p>{item.message}</p></div>)}<div><b>Regla</b><p>El diagnóstico orienta; no ejecuta acciones sobre clientes y mantiene revisión humana.</p></div></div></div></div></section>
}
