import {useEffect,useState} from 'react'
import {buildDiagnosis,runDataset} from './api'
import './diagnosis-brief.css'
import './diagnosis-actions.css'

const pct=v=>`${(Number(v||0)*100).toFixed(1)}%`

export default function DiagnosisBrief({datasetId=''}){
 const [diagnosis,setDiagnosis]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[toast,setToast]=useState('')
 useEffect(()=>{if(datasetId)load(datasetId)},[datasetId])
 async function load(id){setLoading(true);setError('');try{const result=await runDataset(id);const diagnosisResult=await buildDiagnosis({analysis:result?.risk_intelligence||result?.analysis||{},data_quality:result?.risk_intelligence?.data_quality||result?.data_quality,readiness:result?.analysis_readiness||[]});setDiagnosis(diagnosisResult)}catch(e){setError(e.message)}finally{setLoading(false)}}
 function proposePolicy(){const top=diagnosis?.top_driver;const draft={id:`policy-${Date.now()}`,name:top?.name?`Monitoreo ${top.name}`:'Monitoreo de cartera',logic:'AND',mode:'suggested',enabled:true,conditions:[{field:'par30',operator:'gt',value:0.10},{field:'par90',operator:'gt',value:0.02}],actions:[{type:'set_risk_level',parameters:{level:'high'}},{type:'review',parameters:{reason:'Revisar evidencia del diagnóstico'}}]};localStorage.setItem('riskiq.policyDraft',JSON.stringify(draft));setToast('Política sugerida preparada en Decision Engine');setTimeout(()=>setToast(''),3000)}
 function exportBrief(){if(!diagnosis)return;const text=[`RiskIQ — Decision Brief`,``,`Estado: ${diagnosis.headline}`,`Interpretación: ${diagnosis.interpretation}`,``,`Driver: ${diagnosis.top_driver?.name||'No aislable'}`,`Exposición del driver: ${pct(diagnosis.top_driver?.exposure_share)}`,`PAR30 driver: ${pct(diagnosis.top_driver?.par30)}`,`Mora 30+ aportada: ${pct(diagnosis.top_driver?.bad30_contribution)}`,``,`Siguiente análisis: ${diagnosis.next_best_analysis?.model||'—'}`,`Motivo: ${diagnosis.next_best_analysis?.reason||'—'}`,``,`Gobernanza: evidencia determinística, sin causalidad inferida, revisión humana requerida.`].join('\n');const blob=new Blob([text],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`riskiq-decision-brief-${datasetId||'portfolio'}.txt`;a.click();URL.revokeObjectURL(url)}
 if(!datasetId)return null
 const driver=diagnosis?.top_driver
 return <section className="dx-panel"><div className="dx-head"><div><span>DIAGNOSIS ENGINE</span><h2>{diagnosis?.headline||'Diagnóstico de cartera'}</h2><p>{diagnosis?.interpretation||'Construyendo una lectura basada en evidencia determinística.'}</p></div><div className="dx-head-actions"><button onClick={()=>load(datasetId)} disabled={loading}>{loading?'Actualizando…':'Actualizar diagnóstico'}</button><button onClick={proposePolicy} disabled={!diagnosis}>Crear política sugerida</button><button onClick={exportBrief} disabled={!diagnosis}>Exportar brief</button></div></div>{error&&<div className="dx-error">{error}</div>}{toast&&<div className="dx-toast">{toast}</div>}<div className="dx-grid"><div className="dx-card"><span>DRIVER PRINCIPAL</span>{driver?.available?<><strong>{driver.name}</strong><p>{pct(driver.exposure_share)} de exposición · {pct(driver.bad30_contribution)} de la mora 30+</p><small>PAR30 {pct(driver.par30)} · prioridad {driver.priority_score}</small></>:<strong>Sin driver aislable</strong>}</div><div className="dx-card"><span>NEXT BEST ANALYSIS</span><strong>{diagnosis?.next_best_analysis?.model||'—'}</strong><p>{diagnosis?.next_best_analysis?.reason||'Ejecuta el diagnóstico para determinar el siguiente análisis.'}</p></div><div className="dx-card wide"><span>EVIDENCIA</span><div className="dx-evidence">{(diagnosis?.evidence||[]).map(item=><div key={item.metric}><b>{item.metric}</b><strong>{typeof item.value==='number'?(item.unit==='ratio'?pct(item.value):item.value.toLocaleString()):item.value}</strong><small>{item.meaning}</small></div>)}</div></div><div className="dx-card wide"><span>CANDIDATOS A DECISIÓN</span><div className="dx-limitations">{(diagnosis?.decision_candidates||[]).map((item,index)=><div key={index}><b>{item.title}</b><p>Prioridad {item.priority} · revisión humana requerida</p></div>)}{!diagnosis?.decision_candidates?.length&&<div><b>Sin candidato automático</b><p>La evidencia actual no supera un umbral suficiente para proponer una decisión.</p></div>}</div></div><div className="dx-card wide"><span>LIMITACIONES Y GOBERNANZA</span><div className="dx-limitations">{(diagnosis?.limitations||[]).map((item,index)=><div key={index}><b>{item.type}</b><p>{item.message}</p></div>)}<div><b>Regla</b><p>El diagnóstico orienta; no ejecuta acciones sobre clientes y mantiene revisión humana.</p></div></div></div></div></section>
}
