import {useEffect,useState} from 'react'
import {evaluateDecisionFormulas,getDatasetRecords} from './api'
import './indicator-studio.css'

const STARTERS=[
 ['risk_pressure_index','Risk Pressure Index','(par30 * 0.5) + (par60 * 0.3) + (par90 * 0.2)'],
 ['severity_gap','Severity Gap','par90 - par30'],
 ['concentration_pressure','Concentration Pressure','top_concentration_share * top_concentration_par30'],
]

export default function IndicatorStudio({datasetId=''}){
 const [name,setName]=useState('risk_pressure_index'),[label,setLabel]=useState('Risk Pressure Index'),[formula,setFormula]=useState(STARTERS[0][2]),[facts,setFacts]=useState({par30:.1,par60:.06,par90:.02,top_concentration_share:.2,top_concentration_par30:.15}),[result,setResult]=useState(null),[error,setError]=useState(''),[saved,setSaved]=useState(false)
 useEffect(()=>{if(datasetId)loadFacts(datasetId)},[datasetId])
 async function loadFacts(id){try{const raw=await getDatasetRecords(id);const rows=Array.isArray(raw)?raw:(raw?.records||[]);if(!rows.length)return;const balance=rows.reduce((a,r)=>a+Number(r.outstanding_principal||r.outstanding_balance||r.saldo||0),0);const bad=b=>rows.reduce((a,r)=>a+(Number(r.dpd||r.days_past_due||r.dias_mora||0)>=b?Number(r.outstanding_principal||r.outstanding_balance||r.saldo||0):0),0);setFacts(f=>({...f,par30:balance?bad(30)/balance:0,par60:balance?bad(60)/balance:0,par90:balance?bad(90)/balance:0}))}catch{}}
 async function test(){setError('');setResult(null);setSaved(false);try{const r=await evaluateDecisionFormulas({[name]:formula},facts);setResult(r)}catch(e){setError(e.message)}}
 function save(){if(!name.trim()||!result?.facts)return;const savedIndicators=JSON.parse(localStorage.getItem('riskiq.customIndicators')||'[]');const next={id:name.trim(),name:label||name,formula,version:1,preview:result.facts[name.trim()],saved_at:new Date().toISOString()};localStorage.setItem('riskiq.customIndicators',JSON.stringify([next,...savedIndicators.filter(x=>x.id!==next.id)].slice(0,50)));setSaved(true)}
 return <section className="indicator-panel"><div className="indicator-head"><div><span>INDICATOR STUDIO</span><h2>Indicadores personalizados</h2><p>Define una métrica sobre evidencia del portafolio. RiskIQ valida la expresión en un entorno seguro antes de reutilizarla en políticas.</p></div><div className="indicator-badge">FORMULA ENGINE · SANDBOX</div></div><div className="indicator-grid"><div className="indicator-builder"><label>Identificador<input value={name} onChange={e=>setName(e.target.value.replace(/[^a-zA-Z0-9_]/g,''))}/></label><label>Nombre visible<input value={label} onChange={e=>setLabel(e.target.value)}/></label><label>Fórmula<textarea value={formula} onChange={e=>setFormula(e.target.value)} rows={4}/></label><div className="starter-row">{STARTERS.map(x=><button key={x[0]} onClick={()=>{setName(x[0]);setLabel(x[1]);setFormula(x[2]);setSaved(false)}}>{x[1]}</button>)}</div><div className="indicator-actions"><button onClick={test}>Validar y calcular</button><button className="secondary" disabled={!result?.facts} onClick={save}>Guardar indicador</button>{saved&&<span>Guardado en tu biblioteca local</span>}</div>{error&&<div className="indicator-error">{error}</div>}</div><aside className="indicator-side"><span>RESULTADO</span>{result?<><strong>{String(result.facts?.[name]??'—')}</strong><small>Valor calculado con evidencia disponible.</small><div className="formula-trace">{(result.trace||[]).map(x=><div key={x.variable}><b>{x.variable}</b><code>{x.formula}</code><em>{String(x.value)}</em></div>)}</div></>:<div className="indicator-empty">Construye una fórmula y valida el resultado. El motor no ejecuta acciones sobre clientes.</div>}<div className="indicator-facts"><b>Hechos disponibles</b>{Object.entries(facts).map(([k,v])=><span key={k}>{k} = {typeof v==='number'?Number(v).toFixed(4):String(v)}</span>)}</div></aside></div></section>}
