import {useEffect,useMemo,useState} from 'react'
import {getDatasetHistory,listDatasets,runDataset,runSimulator} from './api'
import Builder from './Builder'
import './risk-os.css'

const pct=v=>`${(Number(v||0)*100).toFixed(1)}%`
const money=v=>`$${Number(v||0).toLocaleString(undefined,{maximumFractionDigits:0})}`
const num=v=>Number(v||0).toLocaleString()
const level={critical:'CRÍTICO',high:'ALTO',watch:'VIGILANCIA',control:'CONTROL'}
const nav=[
 ['overview','Centro de mando','Overview','CONTROL'],['portfolio','Cartera','Portfolio','CONTROL'],['analytics','Risk Analytics','Specialist cockpit','ANALYTICS'],['concentration','Concentración','Risk concentration','ANALYTICS'],['cohorts','Vintage & cohortes','Cohort intelligence','ANALYTICS'],['migration','Migración','Roll rate & velocity','ANALYTICS'],['stress','Stress testing','Scenario lab','SCENARIOS'],['decisions','Decision Center','Human review','DECISIONING'],['engine','Decision Engine','Low-code policies','DECISIONING'],['quality','Calidad de datos','Data quality','GOVERNANCE']
]
const groups=[
 {label:'Control',items:['overview','portfolio']},{label:'Risk Analytics',items:['analytics','concentration','cohorts','migration']},{label:'Scenarios',items:['stress']},{label:'Decisioning',items:['decisions','engine']},{label:'Governance',items:['quality']}
]

export default function RiskOperatingSystem(){
 const [datasets,setDatasets]=useState([]),[dataset,setDataset]=useState(null),[result,setResult]=useState(null),[history,setHistory]=useState(null),[page,setPage]=useState('overview'),[loading,setLoading]=useState(false),[error,setError]=useState(''),[stress,setStress]=useState(20),[sim,setSim]=useState(null),[mobile,setMobile]=useState(false),[commandOpen,setCommandOpen]=useState(true)
 useEffect(()=>{(async()=>{try{const d=await listDatasets();const items=d?.datasets||d||[];setDatasets(items);const saved=JSON.parse(localStorage.getItem('riskiq.activeDataset')||'null');const active=items.find(x=>x.dataset_id===saved?.dataset_id)||items[0];if(active){setDataset(active);await execute(active)}}catch(e){setError(e.message)}})()},[])
 async function execute(d=dataset){if(!d?.dataset_id)return;setLoading(true);setError('');try{const r=await runDataset(d.dataset_id);setResult(r);setHistory(await getDatasetHistory(d.dataset_id));setDataset({...d,snapshot:r.snapshot});localStorage.setItem('riskiq.activeDataset',JSON.stringify(d))}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function select(d){setDataset(d);setResult(null);setHistory(null);if(d)await execute(d)}
 const snap=result?.snapshot||{},ri=result?.risk_intelligence||{},adv=result?.advanced_analytics||{},vintage=result?.vintage||{},quality=ri.data_quality||{},concentration=ri.concentration||[],priorities=ri.priorities||[],trend=history?.trend_available===true
 const bad=ri.materiality||{},top=concentration[0],posture=ri.posture||{}
 const title=nav.find(x=>x[0]===page)?.[1]||'Centro de mando'
 const go=id=>setPage(id)
 return <div className="ros-shell">
  <aside className={`ros-sidebar ${mobile?'open':''}`}>
   <div className="ros-brand"><div className="ros-mark">R</div><div><strong>RiskIQ</strong><span>RISK OPERATING SYSTEM</span></div></div>
   <div className="ros-portfolio"><span>CARTERA ACTIVA</span><select value={dataset?.dataset_id||''} onChange={e=>select(datasets.find(x=>x.dataset_id===e.target.value))}><option value="">Seleccionar cartera</option>{datasets.map(d=><option key={d.dataset_id} value={d.dataset_id}>{d.source_name||d.name||d.dataset_id}</option>)}</select></div>
   <div className="ros-nav-label">WORKSPACE</div>
   <div className="ros-command-select">
    <button className="ros-command-trigger" onClick={()=>setCommandOpen(v=>!v)} aria-expanded={commandOpen}><span><b>Control de mando</b><small>Navegación del workspace</small></span><strong>{commandOpen?'⌃':'⌄'}</strong></button>
    {commandOpen&&<nav className="ros-command-menu" aria-label="Control de mando">{groups.map(g=><div className="side-group" key={g.label}><span className="side-group-label">{g.label}</span>{g.items.map(id=>{const x=nav.find(n=>n[0]===id);return <button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);setMobile(false)}}><span className="ros-nav-icon">{icon(id)}</span><span><b>{x[1]}</b><small>{x[2]}</small></span>{id==='engine'&&<em>LOW-CODE</em>}</button>})}</div>)}</nav>}
   </div>
   <div className="ros-side-foot"><span className="online-dot"/> Evidence engine online<div>Human review required</div></div>
  </aside>
  <main className="ros-main">
   <header className="ros-top"><button className="ros-menu" onClick={()=>setMobile(!mobile)}>☰</button><div><span className="ros-kicker">RISK OPERATING SYSTEM / {page.toUpperCase()}</span><h1>{title}</h1></div><div className="ros-top-actions"><span className={`engine-status ${loading?'busy':''}`}><i/>{loading?'Analizando evidencia':'Motor listo'}</span><button className="run-button" onClick={()=>execute()} disabled={!dataset||loading}>{loading?'Procesando…':'Ejecutar análisis'}</button></div></header>
   {error&&<div className="ros-error">{error}</div>}
   {!dataset?<Empty/>:<div className="ros-content">
    {page==='overview'&&<Overview snap={snap} ri={ri} quality={quality} concentration={concentration} priorities={priorities} trend={trend} history={history} onGo={go}/>} 
    {page==='portfolio'&&<Portfolio snap={snap} ri={ri} trend={trend} history={history}/>} 
    {page==='analytics'&&<Analytics snap={snap} ri={ri} concentration={concentration} vintage={vintage} history={history} adv={adv} quality={quality}/>} 
    {page==='concentration'&&<Concentration data={concentration} materiality={bad}/>} 
    {page==='cohorts'&&<Cohorts vintage={vintage}/>} 
    {page==='migration'&&<Migration history={history} adv={adv}/>} 
    {page==='stress'&&<Stress shock={stress} setShock={setStress} sim={sim} run={async()=>{setLoading(true);try{setSim(await runSimulator({dataset_id:dataset.dataset_id,shock_pct:stress/100,scenario_name:`Stress +${stress}% mora`}))}catch(e){setError(e.message)}finally{setLoading(false)}}}/>} 
    {page==='decisions'&&<DecisionCenter priorities={priorities} result={result} onGo={go}/>} 
    {page==='engine'&&<Engine/>}
    {page==='quality'&&<Quality quality={quality} result={result}/>} 
   </div>}
  </main>
 </div>
}

function icon(id){return ({overview:'◈',portfolio:'◫',analytics:'◒',concentration:'⌁',cohorts:'◌',migration:'⇄',stress:'◐',decisions:'✓',engine:'⌘',quality:'▦'})[id]||'•'}
function Empty(){return <div className="ros-empty"><div className="empty-mark">R</div><h2>Selecciona una cartera</h2><p>RiskIQ necesita una cartera cargada para construir evidencia, segmentación y decisiones.</p></div>}
function Section({eyebrow,title,action,children,wide=false}){return <section className={`ros-section ${wide?'wide':''}`}><div className="section-head"><div><span>{eyebrow}</span><h2>{title}</h2></div>{action}</div>{children}</section>}
function Metric({label,value,detail,accent}){return <div className={`ros-metric ${accent||''}`}><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>}

function Overview({snap,ri,quality,concentration,priorities,trend,history,onGo}){const p=ri.posture||{},m=ri.materiality||{},top=concentration[0];return <>
 <div className="ros-hero"><div className="hero-copy"><span className="hero-eyebrow">PORTFOLIO POSTURE · {trend?'HISTÓRICO COMPARABLE':'BASELINE'}</span><h2>{p.label||'Lectura de riesgo disponible'}</h2><p>{ri.interpretation||'Ejecuta el análisis para construir evidencia determinística.'}</p><div className="hero-actions"><button onClick={()=>onGo('analytics')}>Abrir Risk Analytics</button><button className="secondary" onClick={()=>onGo('engine')}>Programar decisión <b>⌘</b></button></div></div><div className={`posture-badge ${p.level||'control'}`}><span>ESTADO</span><strong>{level[p.level]||p.level||'—'}</strong><small>{trend?'Cambio medible disponible':'Sin velocidad inferible'}</small></div></div>
 <div className="metric-strip"><Metric label="Exposición" value={money(snap.outstanding_balance)} detail="saldo pendiente"/><Metric label="Créditos activos" value={num(snap.active_loans)} detail="universo analizado"/><Metric label="PAR30" value={pct(snap.par30)} detail={money(m.bad_balance_30_plus)+' en 30+'} accent="risk"/><Metric label="PAR60" value={pct(snap.par60)} detail={money(m.bad_balance_60_plus)+' en 60+'} accent="risk"/><Metric label="PAR90" value={pct(snap.par90)} detail={money(m.bad_balance_90_plus)+' en 90+'} accent="severe"/><Metric label="Confianza" value={`${quality.score||0}/100`} detail={quality.confidence||'—'}/></div>
 <div className="analysis-grid"><Section eyebrow="RISK EXPOSURE" title="Materialidad del deterioro"><div className="exposure-bars"><ExposureBar label="30+" value={m.bad_balance_30_plus} total={m.exposure}/><ExposureBar label="60+" value={m.bad_balance_60_plus} total={m.exposure}/><ExposureBar label="90+" value={m.bad_balance_90_plus} total={m.exposure}/></div><div className="money-insight"><span>Mayor carga económica</span><strong>{money(m.bad_balance_30_plus)}</strong><small>exposición en mora 30+</small></div></Section><Section eyebrow="TRAJECTORY" title="Qué sabemos del cambio"><TrendPanel trend={trend} history={history} onGo={()=>onGo('migration')}/></Section></div>
 <div className="analysis-grid lower"><Section eyebrow="CONCENTRATION" title="Dónde se concentra el deterioro" action={<button className="text-button" onClick={()=>onGo('concentration')}>Ver análisis →</button>}>{top?<div className="focus-row"><div><span>FOCO #1</span><strong>{top.name}</strong><p>{pct(top.exposure_share)} de la exposición · PAR30 {pct(top.par30)}</p></div><div className="focus-number"><strong>{pct(top.contribution_to_portfolio_bad_30)}</strong><span>de la mora 30+ del portafolio</span></div></div>:<p className="muted">No existe dimensión suficiente para localizar concentración.</p>}</Section><Section eyebrow="DECISION QUEUE" title="Prioridades de investigación" action={<button className="text-button" onClick={()=>onGo('decisions')}>Abrir cola →</button>}><PriorityList priorities={priorities.slice(0,3)}/></Section></div>
 <div className="ros-next"><div><span>NEXT BEST ANALYSIS</span><strong>{top?`Descomponer ${top.name} por vintage, DPD y transición.`:'Añadir cortes históricos para medir velocidad y migración.'}</strong></div><button onClick={()=>onGo(top?'cohorts':'quality')}>Continuar análisis →</button></div>
 </>}

function Portfolio({snap,ri,trend,history}){const m=ri.materiality||{};return <><Section eyebrow="PORTFOLIO POSITION" title="Perfil de riesgo actual"><div className="metric-strip embedded"><Metric label="PAR7" value={pct(snap.par7)} detail="entrada temprana"/><Metric label="PAR30" value={pct(snap.par30)} detail="mora 30+" accent="risk"/><Metric label="PAR60" value={pct(snap.par60)} detail="mora 60+" accent="risk"/><Metric label="PAR90" value={pct(snap.par90)} detail="mora severa" accent="severe"/></div></Section><div className="analysis-grid"><Section eyebrow="ECONOMIC MATERIALITY" title="Saldo comprometido"><DataRows rows={[["Exposición total",money(m.exposure)],["1+ días",money(m.bad_balance_1_plus)],["30+ días",money(m.bad_balance_30_plus)],["60+ días",money(m.bad_balance_60_plus)],["90+ días",money(m.bad_balance_90_plus)]]}/></Section><Section eyebrow="HISTORY" title={trend?'Comparación disponible':'Baseline sin tendencia'}>{trend?<DataRows rows={[["Corte anterior",history?.previous_snapshot_date||'—'],["Corte actual",history?.current_snapshot_date||'—'],["Delta PAR30",pct(history?.changes?.par30?.delta||0)]]}/>:<div className="empty-analysis"><strong>Un corte describe estado, no velocidad.</strong><p>RiskIQ no inventa estabilidad ni deterioro sin un corte comparable de la misma cartera.</p></div>}</Section></div></>}

function Analytics({snap,ri,concentration,vintage,history,adv,quality}){const m=ri.materiality||{},par=[snap.par7,snap.par30,snap.par60,snap.par90].map(Number),top3=concentration.slice(0,3).reduce((a,x)=>a+Number(x.exposure_share||0),0),hhi=concentration.reduce((a,x)=>a+Math.pow(Number(x.exposure_share||0),2),0),riskEfficiency=Number(snap.par30||0)&&Number(snap.par90||0)?Number(snap.par90)/Number(snap.par30):null;return <>
 <div className="analytics-command"><div><span>SPECIALIST COCKPIT</span><h2>Risk Analytics</h2><p>Lectura cuantitativa para riesgo de crédito: severidad, concentración, vintage y trayectoria.</p></div><div className="analytics-meta"><span>DATA CONFIDENCE</span><strong>{quality.score||0}/100</strong><small>{quality.confidence||'—'}</small></div></div>
 <div className="metric-strip analytics-metrics"><Metric label="PAR30 / PAR90" value={riskEfficiency?riskEfficiency.toFixed(2)+'x':'—'} detail="severidad relativa" accent="risk"/><Metric label="Top 3 share" value={pct(top3)} detail="concentración de exposición"/><Metric label="HHI" value={hhi?Math.round(hhi*10000):'—'} detail="concentración · derivado"/><Metric label="Bad 30+" value={money(m.bad_balance_30_plus)} detail="materialidad económica" accent="risk"/></div>
 <div className="advanced-grid"><Section eyebrow="DELINQUENCY CURVE" title="Estructura de mora"><RiskCurve values={par}/></Section><Section eyebrow="CONCENTRATION PROFILE" title="Exposición vs deterioro"><ConcentrationChart data={concentration}/></Section></div>
 <div className="advanced-grid"><Section eyebrow="VINTAGE RISK" title="Riesgo por generación"><VintageChart vintages={vintage?.vintages||[]}/></Section><Section eyebrow="PORTFOLIO SIGNALS" title="Indicadores derivados"><SignalMatrix snap={snap} ri={ri} history={history} adv={adv}/></Section></div>
 <div className="analytics-note"><strong>Metodología</strong><span>Los indicadores derivados se calculan únicamente sobre evidencia cargada. RiskIQ no convierte ausencia de snapshots en tendencia ni inventa roll rates.</span></div>
 </>}

function RiskCurve({values}){const labels=['PAR7','PAR30','PAR60','PAR90'],max=Math.max(...values,0.01),pts=values.map((v,i)=>`${24+i*100},${156-(Number(v||0)/max)*120}`).join(' ');return <div className="chart-shell"><div className="chart-value-row">{values.map((v,i)=><div key={labels[i]}><span>{labels[i]}</span><strong>{pct(v)}</strong></div>)}</div><svg className="risk-svg" viewBox="0 0 348 180" role="img" aria-label="Curva PAR7 a PAR90"><line x1="24" y1="156" x2="324" y2="156"/><line x1="24" y1="36" x2="324" y2="36"/><polyline points={pts}/>{values.map((v,i)=>{const y=156-(Number(v||0)/max)*120;return <g key={i}><circle cx={24+i*100} cy={y} r="5"/><text x={24+i*100} y="174" textAnchor="middle">{labels[i]}</text></g>})}</svg><div className="chart-foot"><span>Escala relativa al máximo observado</span><span>Estado actual</span></div></div>}
function ConcentrationChart({data}){const rows=data.slice(0,6),max=Math.max(...rows.map(x=>Number(x.exposure_share||0)),0.01);return <div className="bar-chart">{rows.length?rows.map(x=><div className="bar-row" key={x.name}><div><span>{x.name}</span><b>{pct(x.exposure_share)}</b></div><div className="bar-track"><i style={{width:`${Math.min(100,Number(x.exposure_share||0)/max*100)}%`}}/></div><small>PAR30 {pct(x.par30)} · aporte 30+ {pct(x.contribution_to_portfolio_bad_30)}</small></div>):<div className="empty-analysis">No hay segmentación suficiente.</div>}</div>}
function VintageChart({vintages}){const rows=vintages.slice(0,8),max=Math.max(...rows.map(x=>Number(x.par30||0)),0.01);return <div className="vintage-chart">{rows.length?rows.map(x=><div className="vintage-row" key={x.vintage||x.period}><span>{x.vintage||x.period}</span><div className="vintage-track"><i style={{width:`${Math.min(100,Number(x.par30||0)/max*100)}%`}}/></div><strong>{pct(x.par30)}</strong></div>):<div className="empty-analysis">Se requieren fechas de originación para comparar vintages.</div>}</div>}
function SignalMatrix({snap,ri,history,adv}){const p7=Number(snap.par7||0),p30=Number(snap.par30||0),p60=Number(snap.par60||0),p90=Number(snap.par90||0),early=p7>0?p30/p7:null,severe=p30>0?p90/p30:null,delta=history?.changes?.par30?.delta;const signals=[['Early deterioration',early?early.toFixed(2)+'x':'—','PAR30 / PAR7'],['Severe conversion',severe?severe.toFixed(2)+'x':'—','PAR90 / PAR30'],['PAR30 delta',delta!==undefined?pct(delta):'—','vs prior comparable'],['Migration engine',adv?.migration?.available?'READY':'BASELINE','historical evidence']];return <div className="signal-grid">{signals.map(([a,b,c])=><div key={a}><span>{a}</span><strong>{b}</strong><small>{c}</small></div>)}</div>}

function Concentration({data}){return <><Section eyebrow="RISK CONCENTRATION" title="Contribución al deterioro"><div className="table-wrap"><table><thead><tr><th>Segmento</th><th>Exposición</th><th>Share</th><th>PAR30</th><th>Contribución 30+</th><th>Priority</th></tr></thead><tbody>{data.map((x,i)=><tr key={x.name}><td><b>{i===0?'01 ':''}{x.name}</b></td><td>{money(x.exposure)}</td><td>{pct(x.exposure_share)}</td><td>{pct(x.par30)}</td><td><strong>{pct(x.contribution_to_portfolio_bad_30)}</strong></td><td><span className="priority-pill">{x.priority_score}</span></td></tr>)}</tbody></table>{!data.length&&<div className="empty-analysis">No hay una dimensión de segmentación suficiente.</div>}</div></Section><div className="formula-panel"><div><span>ANALYTICAL LOGIC</span><strong>Contribución a mora = exposición × deterioro</strong></div><p>Un segmento pequeño con PAR alto puede ser menos material que uno grande con deterioro moderado. RiskIQ prioriza impacto económico, no solo porcentaje.</p></div></>}
function Cohorts({vintage}){const vs=vintage?.vintages||[],b=vintage?.buckets||[];return <><Section eyebrow="VINTAGE INTELLIGENCE" title="Riesgo por generación"><div className="table-wrap"><table><thead><tr><th>Vintage</th><th>Créditos</th><th>Saldo</th><th>PAR30</th><th>PAR90</th></tr></thead><tbody>{vs.map(x=><tr key={x.vintage||x.period}><td><b>{x.vintage||x.period}</b></td><td>{num(x.loans)}</td><td>{money(x.balance||x.exposure)}</td><td>{pct(x.par30)}</td><td>{pct(x.par90)}</td></tr>)}</tbody></table>{!vs.length&&<div className="empty-analysis">{(vintage?.warnings||[]).join(' ')||'Se requieren fechas de originación para habilitar vintage.'}</div>}</div></Section><Section eyebrow="DPD DISTRIBUTION" title="Composición de la mora"><div className="bucket-grid">{b.map(x=><div key={x.bucket||x.label}><span>{x.bucket||x.label}</span><strong>{num(x.loans)}</strong><small>{money(x.exposure||x.balance)}</small></div>)}</div></Section></>}
function Migration({history,adv}){const m=adv?.migration||{};return <><Section eyebrow="MIGRATION INTELLIGENCE" title="Velocidad del deterioro"><div className="migration-hero"><div><span>STATUS</span><strong>{m.available?'Comparación habilitada':'Sin comparación histórica'}</strong><p>{m.available?`PAR30 ${pct(m.previous_par30)} → ${pct(m.current_par30)} · variación ${pct(m.delta_par30)}`:'No se calcula velocidad con un único corte.'}</p></div><div className={`direction ${m.direction||'baseline'}`}>{m.direction||'BASELINE'}</div></div></Section><Section eyebrow="ROLL RATE & SNAPSHOTS" title="Transición entre estados"><div className="timeline-empty"><strong>{history?.count||0} snapshot(s) registrado(s)</strong><p>Para roll rates comparables se requiere la misma identidad de crédito en snapshots consecutivos. Sin esa evidencia, el motor no fabrica tasas de migración.</p></div></Section></>}
function Stress({shock,setShock,sim,run}){return <><Section eyebrow="SCENARIO LAB" title="Stress testing de cartera"><div className="stress-control"><div><span>SHOCK DE MORA</span><strong>+{shock}%</strong><p>Escenario hipotético. No modifica la cartera real.</p></div><input type="range" min="5" max="50" step="5" value={shock} onChange={e=>setShock(Number(e.target.value))}/><button className="run-button" onClick={run}>Ejecutar escenario</button></div>{sim&&<pre className="scenario-result">{JSON.stringify(sim,null,2)}</pre>}</Section></>}
function DecisionCenter({priorities,result,onGo}){const cards=result?.workspace?.decision_center?.cards||result?.decision_engine?.decisions||[];return <><div className="decision-hero"><div><span>DECISION CENTER</span><h2>Evidencia → decisión → revisión humana</h2><p>Las recomendaciones son auditables y no ejecutan acciones automáticamente.</p></div><button className="run-button" onClick={()=>onGo('engine')}>Programar política <b>⌘</b></button></div><Section eyebrow="REVIEW QUEUE" title={`${priorities.length||cards.length} prioridad(es) activas`}><PriorityList priorities={priorities}/>{!priorities.length&&cards.map((x,i)=><div className="decision-card" key={i}><span>{x.priority||'REVISAR'}</span><strong>{x.title||x.reason||'Decisión'}</strong><p>{x.suggested_action||x.evidence||'Revisión requerida.'}</p></div>)}</Section></>}
function Engine(){return <div className="engine-page"><div className="engine-intro"><div><span>DECISION ENGINE · LOW-CODE</span><h2>Programa cómo RiskIQ decide</h2><p>Construye políticas reutilizables con condiciones, operadores, resultados y modos de ejecución. Valida, prueba y guarda desde la plataforma.</p></div><div className="engine-chip">AUDITABLE · HUMAN CONTROL</div></div><Builder/></div>}
function Quality({quality}){const limits=quality.limitations||[],warnings=quality.warnings||[];return <><Section eyebrow="DATA QUALITY" title={`Confianza analítica · ${quality.score||0}/100`}><div className="quality-head"><div className="quality-score">{quality.score||0}<small>/100</small></div><div><strong>{quality.confidence||'Sin clasificar'}</strong><p>La confianza refleja calidad y disponibilidad de evidencia, no la gravedad del riesgo.</p></div></div></Section><div className="analysis-grid"><Section eyebrow="LIMITATIONS" title="Qué todavía no podemos afirmar"><ul className="clean-list">{[...warnings,...limits].map((x,i)=><li key={i}>{x}</li>)}</ul></Section><Section eyebrow="GOVERNANCE" title="Principios de evidencia"><ul className="clean-list"><li>Un corte único se presenta como baseline, no como tendencia.</li><li>NPL es proxy analítico cuando no existe definición contractual/regulatoria.</li><li>Las políticas del Decision Engine son configurables e internas.</li><li>Las acciones requieren revisión humana.</li></ul></Section></div></>}
function ExposureBar({label,value,total}){const w=total?Math.min(100,value/total*100):0;return <div className="exposure-bar"><div><span>{label} exposición</span><b>{money(value)}</b></div><div><i style={{width:`${w}%`}}/></div></div>}
function TrendPanel({trend,history,onGo}){if(!trend)return <div className="trend-empty"><div className="trend-icon">⌁</div><div><strong>Sin tendencia defendible</strong><p>Un solo corte describe estado, no velocidad. Carga otro snapshot comparable para medir deterioro o mejora.</p><button onClick={onGo}>Abrir migración →</button></div></div>;return <div className="trend-panel"><div><strong>Comparación disponible</strong><p>{history?.previous_snapshot_date||'Anterior'} → {history?.current_snapshot_date||'Actual'}</p></div><div className="sparkline"><span/><span/><span/><span/><span/></div><b>{pct(history?.changes?.par30?.delta||0)} Δ PAR30</b></div>}
function PriorityList({priorities}){return <div className="priority-list">{priorities.length?priorities.map(x=><div className="priority-row" key={`${x.rank}-${x.title}`}><span>#{x.rank}</span><div><strong>{x.title}</strong><p>{x.why}</p><small>{Object.entries(x.evidence||{}).slice(0,3).map(([k,v])=>`${k}: ${typeof v==='number'?(v<1?pct(v):v.toLocaleString()):v}`).join(' · ')}</small></div></div>):<div className="empty-analysis">No hay prioridades calculadas con la evidencia disponible.</div>}</div>}
function DataRows({rows}){return <div className="data-rows">{rows.map(([a,b])=><div key={a}><span>{a}</span><strong>{b}</strong></div>)}</div>}
