import {useEffect,useMemo,useState} from 'react'
import {getDatasetHistory,listDatasets,runDataset,runSimulator} from './api'
import './risk-command-center.css'

const pct=v=>`${(Number(v||0)*100).toFixed(1)}%`
const money=v=>`$${Number(v||0).toLocaleString(undefined,{maximumFractionDigits:0})}`
const n=v=>Number(v||0).toLocaleString()
const levelLabel={critical:'Crítico',high:'Alto',watch:'Vigilancia',control:'Control'}

export default function RiskCommandCenter(){
 const [datasets,setDatasets]=useState([]),[dataset,setDataset]=useState(null),[result,setResult]=useState(null),[history,setHistory]=useState(null),[page,setPage]=useState('Command Center'),[loading,setLoading]=useState(false),[error,setError]=useState(''),[sim,setSim]=useState(null),[shock,setShock]=useState(20)
 useEffect(()=>{(async()=>{try{const ds=await listDatasets();setDatasets(ds?.datasets||ds||[]);const saved=JSON.parse(localStorage.getItem('riskiq.activeDataset')||'null');const d=(ds?.datasets||ds||[]).find(x=>x.dataset_id===saved?.dataset_id)||(ds?.datasets||ds||[])[0];if(d){setDataset(d);await execute(d)}}catch(e){setError(e.message)}})()},[])
 async function execute(d=dataset){if(!d?.dataset_id)return;setLoading(true);setError('');try{const r=await runDataset(d.dataset_id);setResult(r);setDataset({...d,snapshot:r.snapshot});setHistory(await getDatasetHistory(d.dataset_id));localStorage.setItem('riskiq.activeDataset',JSON.stringify(d))}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function select(d){setDataset(d);setResult(null);try{const h=await getDatasetHistory(d.dataset_id);setHistory(h);await execute(d)}catch(e){setError(e.message)}}
 const ri=result?.risk_intelligence||{};const snap=result?.snapshot||{};const adv=result?.advanced_analytics||{};const risk=result?.risk_analytics?.deterministic||{};const par=risk.par||{};const concentration=ri.concentration||[];const priorities=ri.priorities||[];const quality=ri.data_quality||{};const vintage=result?.vintage||{};const trend=history?.trend_available===true
 const bad30=ri.materiality?.bad_balance_30_plus||0
 const top=concentration[0]
 const nav=[['Command Center','Centro de mando'],['Portfolio','Cartera'],['Concentration','Concentración'],['Cohorts','Vintage & cohortes'],['Migration','Migración'],['Stress','Stress testing'],['Decisions','Decisiones'],['Data Quality','Calidad de datos']]
 return <div className="rc-shell"><aside className="rc-side"><div className="rc-brand"><span>R</span><div><b>RiskIQ</b><small>Risk Operating System</small></div></div><div className="rc-selector"><label>CARTERA ACTIVA</label><select value={dataset?.dataset_id||''} onChange={e=>select(datasets.find(x=>x.dataset_id===e.target.value))}><option value="">Sin cartera</option>{datasets.map(d=><option key={d.dataset_id} value={d.dataset_id}>{d.source_name||d.name||d.dataset_id}</option>)}</select></div><nav>{nav.map(([id,label])=><button className={page===id?'active':''} onClick={()=>setPage(id)} key={id}><span>{label}</span></button>)}</nav><div className="rc-foot"><i/> Evidencia determinística<br/><small>Decisiones requieren revisión humana</small></div></aside><main className="rc-main"><header className="rc-top"><div><span className="rc-kicker">RISK OPERATING SYSTEM / {page.toUpperCase()}</span><h1>{nav.find(x=>x[0]===page)?.[1]}</h1></div><div className="rc-actions"><span className={`rc-status ${loading?'busy':''}`}>{loading?'Procesando evidencia':'Motor listo'}</span><button onClick={()=>execute()} disabled={!dataset||loading}>{loading?'Analizando…':'Ejecutar análisis'}</button></div></header>{error&&<div className="rc-error">{error}</div>}{!dataset?<Empty/>:<>{page==='Command Center'&&<Command snap={snap} ri={ri} adv={adv} trend={trend} top={top} priorities={priorities} quality={quality} onGo={setPage}/>} {page==='Portfolio'&&<Portfolio snap={snap} par={par} ri={ri} trend={trend} history={history}/>} {page==='Concentration'&&<Concentration data={concentration} bad30={bad30}/>} {page==='Cohorts'&&<Cohorts vintage={vintage}/>} {page==='Migration'&&<Migration history={history} adv={adv}/>} {page==='Stress'&&<Stress shock={shock} setShock={setShock} sim={sim} run={async()=>{setLoading(true);try{setSim(await runSimulator({dataset_id:dataset.dataset_id,shock_pct:shock/100,scenario_name:`Stress +${shock}% mora`}))}catch(e){setError(e.message)}finally{setLoading(false)}}} snap={snap}/>} {page==='Decisions'&&<Decisions priorities={priorities} result={result}/>} {page==='Data Quality'&&<Quality quality={quality}/>}</>}</main></div>
}
function Shell({title,eyebrow,children}){return <section className="rc-section"><div className="rc-section-head"><div><span>{eyebrow}</span><h2>{title}</h2></div></div>{children}</section>}
function Metric({label,value,detail}){return <div className="rc-metric"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>}
function Command({snap,ri,adv,trend,top,priorities,quality,onGo}){const p=ri.posture||{};const m=ri.materiality||{};return <div className="rc-page"><div className="rc-hero"><div><span>PORTFOLIO POSTURE</span><h2>{p.label||'Sin lectura'}</h2><p>{ri.interpretation||'Ejecuta el análisis para construir evidencia.'}</p></div><div className={`rc-posture ${p.level||'control'}`}><b>{levelLabel[p.level]||p.level||'—'}</b><small>{trend?'Histórico comparable':'Baseline · sin tendencia'}</small></div></div><div className="rc-metrics"><Metric label="Exposición" value={money(snap.outstanding_balance)} detail="Saldo pendiente"/><Metric label="Créditos" value={n(snap.active_loans)} detail="Cartera activa"/><Metric label="30+" value={pct(snap.par30)} detail={money(m.bad_balance_30_plus)+' expuesta'}/><Metric label="60+" value={pct(snap.par60)} detail={money(m.bad_balance_60_plus)+' expuesta'}/><Metric label="90+" value={pct(snap.par90)} detail={money(m.bad_balance_90_plus)+' expuesta'}/><Metric label="Confianza datos" value={`${quality.score||0}/100`} detail={quality.confidence||'—'}/></div><div className="rc-grid-2"><Shell eyebrow="RIESGO ECONÓMICO" title="La cartera no se resume en un porcentaje"><div className="rc-bars"><Bar label="30+ exposición" value={m.bad_balance_30_plus} total={m.exposure}/><Bar label="60+ exposición" value={m.bad_balance_60_plus} total={m.exposure}/><Bar label="90+ exposición" value={m.bad_balance_90_plus} total={m.exposure}/></div><div className="rc-callout"><b>{top?`Foco principal: ${top.name}`:'Falta segmentación'}</b><span>{top?`${pct(top.exposure_share)} de exposición · ${pct(top.contribution_to_portfolio_bad_30)} de la mora 30+`:'Carga una dimensión de segmentación para localizar el riesgo.'}</span></div></Shell><Shell eyebrow="TRAYECTORIA" title="Qué sabemos del cambio"><div className="rc-trend"><b>{trend?'Hay comparación histórica':'No hay tendencia defendible'}</b><p>{trend?'El motor puede medir variación entre cortes.':'Un solo corte describe estado, no velocidad. No se inventan deltas ni estabilidad.'}</p><button onClick={()=>onGo('Migration')}>Abrir migración</button></div></Shell></div><Shell eyebrow="PRIORIZACIÓN" title="Dónde poner atención primero"><div className="rc-priorities">{priorities.length?priorities.map(x=><div className="rc-priority" key={`${x.type}-${x.title}`}><b>#{x.rank} · {x.title}</b><p>{x.why}</p><code>{Object.entries(x.evidence||{}).map(([k,v])=>`${k}: ${typeof v==='number'?(v<1?pct(v):v.toLocaleString()):v}`).join(' · ')}</code></div>):<div className="rc-empty">No hay prioridades suficientes con la evidencia disponible.</div>}</div></Shell><div className="rc-next"><b>Siguiente nivel</b><span>{top?`Descomponer ${top.name} por vintage, DPD y concentración de mora.`:'Añadir segmentación y fechas históricas para habilitar causalidad operativa.'}</span><button onClick={()=>onGo(top?'Concentration':'Data Quality')}>Continuar análisis</button></div></div>}
function Bar({label,value,total}){const w=total?Math.min(100,value/total*100):0;return <div className="rc-bar"><div><span>{label}</span><b>{money(value)}</b></div><div className="rc-track"><i style={{width:`${w}%`}}/></div></div>}
function Portfolio({snap,par,ri,trend,history}){return <div className="rc-page"><Shell eyebrow="POSICIÓN" title="Perfil completo de exposición"><div className="rc-metrics rc-metrics-4"><Metric label="PAR7" value={pct(snap.par7)} detail="Entrada temprana"/><Metric label="PAR30" value={pct(snap.par30)} detail="Mora 30+"/><Metric label="PAR60" value={pct(snap.par60)} detail="Mora 60+"/><Metric label="PAR90" value={pct(snap.par90)} detail="Mora 90+"/></div></Shell><div className="rc-grid-2"><Shell eyebrow="MATERIALIDAD" title="Dinero en riesgo"><DataList items={[["1+ días",money(ri.materiality?.bad_balance_1_plus)],["30+ días",money(ri.materiality?.bad_balance_30_plus)],["60+ días",money(ri.materiality?.bad_balance_60_plus)],["90+ días",money(ri.materiality?.bad_balance_90_plus)]]}/></Shell><Shell eyebrow="HISTÓRICO" title={trend?'Comparación disponible':'Baseline'}>{trend?<DataList items={[["Corte anterior",history?.previous_snapshot_date||'—'],["Corte actual",history?.current_snapshot_date||'—'],["Cambios",JSON.stringify(history?.changes||{})]]}/>:<p className="rc-muted">Se necesita otro corte comparable de la misma cartera. RiskIQ no etiqueta una cartera de un solo corte como estable.</p>}</Shell></div></div>}
function Concentration({data,bad30}){return <div className="rc-page"><Shell eyebrow="CONCENTRACIÓN" title="Contribución al deterioro, no solo tamaño"><div className="rc-table"><div className="rc-tr"><b>Segmento</b><b>Exposición</b><b>30+</b><b>Contribución mora</b><b>Prioridad</b></div>{data.map(x=><div className="rc-tr" key={x.name}><span>{x.name}</span><span>{money(x.exposure)} · {pct(x.exposure_share)}</span><span>{pct(x.par30)}</span><span>{pct(x.contribution_to_portfolio_bad_30)}</span><strong>{x.priority_score}</strong></div>)}</div>{!data.length&&<p className="rc-muted">No existe dimensión suficiente para localizar concentración.</p>}</Shell><div className="rc-insight">La contribución a mora 30+ responde a <b>exposición × deterioro</b>. Un segmento pequeño con PAR alto puede ser menos material que uno grande con deterioro moderado.</div></div>}
function Cohorts({vintage}){const vs=vintage?.vintages||[];const buckets=vintage?.buckets||[];const rr=vintage?.roll_rates||[];return <div className="rc-page"><div className="rc-grid-2"><Shell eyebrow="VINTAGE" title="Riesgo por generación"><div className="rc-table compact"><div className="rc-tr"><b>Vintage</b><b>Créditos</b><b>Saldo</b><b>PAR30</b><b>PAR90</b></div>{vs.map(x=><div className="rc-tr" key={x.vintage||x.period}><span>{x.vintage||x.period}</span><span>{n(x.loans)}</span><span>{money(x.balance||x.exposure)}</span><span>{pct(x.par30)}</span><span>{pct(x.par90)}</span></div>)}</div>{!vs.length&&<p className="rc-muted">{(vintage?.warnings||[]).join(' ')||'Sin vintage disponible.'}</p>}</Shell><Shell eyebrow="DISTRIBUCIÓN DPD" title="Dónde está la mora"><DataList items={buckets.map(x=>[x.bucket||x.label,n(x.loans)+' · '+money(x.exposure||x.balance)])}/></Shell></div><Shell eyebrow="ROLL RATE" title="Migración entre estados"><div className="rc-table compact"><div className="rc-tr"><b>Desde</b><b>Hacia</b><b>Créditos</b><b>Exposición</b><b>Tasa</b></div>{rr.map((x,i)=><div className="rc-tr" key={i}><span>{x.from}</span><span>{x.to}</span><span>{n(x.loans)}</span><span>{money(x.exposure)}</span><strong>{pct(x.rate)}</strong></div>)}</div>{!rr.length&&<p className="rc-muted">{(vintage?.warnings||[]).join(' ')||'No hay transición calculable. Se requieren al menos dos cortes y la misma identidad de crédito.'}</p>}</Shell></div>}
function Migration({history,adv}){const m=adv?.migration||{};return <div className="rc-page"><Shell eyebrow="MIGRACIÓN" title="Velocidad del deterioro"><div className="rc-hero mini"><div><h2>{m.available?'Comparación habilitada':'Sin comparación histórica'}</h2><p>{m.available?`PAR30 ${pct(m.previous_par30)} → ${pct(m.current_par30)} · ${pct(m.delta_par30)} de variación.`:'No se calcula velocidad con un único corte.'}</p></div><span>{m.direction||'baseline'}</span></div><p className="rc-muted">La tendencia responde a cortes comparables. Para roll rates, además, RiskIQ exige la misma identidad de crédito en snapshots consecutivos.</p></Shell></div>}
function Stress({shock,setShock,sim,run,snap}){return <div className="rc-page"><Shell eyebrow="SCENARIO LAB" title="¿Cuánto cambia la exposición si empeora la mora?"><div className="rc-slider"><label>Shock de mora: <b>+{shock}%</b></label><input type="range" min="5" max="50" step="5" value={shock} onChange={e=>setShock(Number(e.target.value))}/><button onClick={run}>Ejecutar escenario</button></div>{sim&&<pre className="rc-result">{JSON.stringify(sim,null,2)}</pre>}<p className="rc-muted">Stress testing es hipotético: no pronostica resultados ni modifica la cartera real.</p></Shell></div>}
function Decisions({priorities,result}){const cards=result?.workspace?.decision_center?.cards||result?.decision_engine?.decisions||[];return <div className="rc-page"><Shell eyebrow="DECISION CENTER" title="Evidencia → revisión humana"><div className="rc-decision-list">{priorities.map(x=><div className="rc-decision" key={x.title}><span>REVISAR</span><b>{x.title}</b><p>{x.why}</p><code>{JSON.stringify(x.evidence)}</code></div>)}{!priorities.length&&cards.map((x,i)=><div className="rc-decision" key={i}><span>{x.priority||'REVISAR'}</span><b>{x.title||x.reason||'Decisión'}</b><p>{x.suggested_action||x.evidence||''}</p></div>)}</div></Shell></div>}
function Quality({quality}){return <div className="rc-page"><Shell eyebrow="DATA QUALITY" title={`Confianza analítica · ${quality.score||0}/100`}><div className="rc-table"><div className="rc-tr"><b>Campo</b><b>Cobertura</b><b>Estado</b></div>{(quality.checks||[]).map(x=><div className="rc-tr" key={x.field}><span>{x.label}</span><span>{pct(x.coverage)}</span><strong>{x.status}</strong></div>)}</div><p className="rc-muted">{quality.limitation}</p></Shell></div>}
function DataList({items}){return <div className="rc-data-list">{items.map(([a,b],i)=><div key={i}><span>{a}</span><b>{b}</b></div>)}</div>}
function Empty(){return <div className="rc-empty-page"><h2>Conecta una cartera</h2><p>RiskIQ necesita datos para construir evidencia de exposición, deterioro, concentración y decisiones.</p></div>}
