import {useEffect,useMemo,useState} from 'react'
import {archiveSegment,listSegments,previewSegment,saveSegment} from './api'
import './segment-studio.css'

const OPS=[['=','igual a'],['!=','distinto de'],['>','mayor que'],['>=','mayor o igual'],['<','menor que'],['<=','menor o igual'],['contains','contiene'],['is_empty','está vacío'],['is_not_empty','no está vacío']]

export default function SegmentStudio({datasetId='',columns=[]}){
 const [segments,setSegments]=useState([]),[name,setName]=useState(''),[conditions,setConditions]=useState([{field:'',operator:'=',value:''}]),[preview,setPreview]=useState(null),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('')
 const fields=useMemo(()=>columns.map(c=>typeof c==='string'?c:c.name).filter(Boolean),[columns])
 useEffect(()=>{if(datasetId)load()},[datasetId])
 async function load(){try{const r=await listSegments(datasetId);setSegments(r?.segments||[])}catch(e){setError(e.message)}}
 function update(i,key,value){setConditions(cs=>cs.map((c,n)=>n===i?{...c,[key]:value}:c))}
 function add(){setConditions(cs=>[...cs,{field:fields[0]||'',operator:'=',value:''}])}
 function remove(i){setConditions(cs=>cs.length===1?cs:cs.filter((_,n)=>n!==i))}
 async function runPreview(){setLoading(true);setError('');try{setPreview((await previewSegment(datasetId,conditions)).preview)}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function save(){if(!name.trim())return setError('Indica un nombre para el segmento.');setSaving(true);setError('');try{await saveSegment(datasetId,{name:name.trim(),conditions});await load();setName('');setPreview(null)}catch(e){setError(e.message)}finally{setSaving(false)}}
 async function archive(name){try{await archiveSegment(datasetId,name);await load()}catch(e){setError(e.message)}}
 if(!datasetId)return null
 return <div className="df-card wide segment-studio"><div className="df-card-title"><div><span>SEGMENTATION LAB</span><strong>Segmentación personalizada</strong></div><span>Ad hoc · reutilizable · basada en datos fuente</span></div><p>Construye cortes como <b>edad ≥ 30</b>, <b>empleado</b> o <b>sin vehículo</b> sin alterar el dato original. Los segmentos se calculan sobre el último estado disponible de cada crédito.</p>{error&&<div className="df-error">{error}</div>}<div className="segment-builder">{conditions.map((c,i)=><div className="segment-condition" key={i}><select value={c.field} onChange={e=>update(i,'field',e.target.value)}><option value="">Campo…</option>{fields.map(f=><option key={f} value={f}>{f}</option>)}</select><select value={c.operator} onChange={e=>update(i,'operator',e.target.value)}>{OPS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>{!['is_empty','is_not_empty'].includes(c.operator)&&<input value={c.value} onChange={e=>update(i,'value',e.target.value)} placeholder="Valor…"/>}<button type="button" onClick={()=>remove(i)} disabled={conditions.length===1}>×</button></div>)}<div className="segment-actions"><button type="button" onClick={add}>+ Condición</button><button type="button" onClick={runPreview} disabled={loading}>{loading?'Calculando…':'Previsualizar'}</button></div></div>{preview&&<div className="segment-preview"><div><span>CRÉDITOS</span><strong>{Number(preview.rows||0).toLocaleString()}</strong></div><div><span>EXPOSICIÓN</span><strong>${Number(preview.exposure||0).toLocaleString()}</strong></div><div><span>PAR30</span><strong>{(Number(preview.par30||0)*100).toFixed(1)}%</strong></div><div><span>PAR90</span><strong>{(Number(preview.par90||0)*100).toFixed(1)}%</strong></div></div>}<div className="segment-save"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nombre del segmento · Ej. Empleados 30+"/><button type="button" onClick={save} disabled={saving||!conditions.some(c=>c.field)}>{saving?'Guardando…':'Guardar segmento'}</button></div>{segments.length>0&&<div className="segment-list"><div className="segment-list-head"><span>SEGMENTOS GUARDADOS</span><span>{segments.length}</span></div>{segments.map(s=><div className="segment-row" key={s.name}><div><b>{s.name}</b><small>{(s.conditions||[]).map(c=>`${c.field} ${c.operator} ${c.value??''}`).join(' · ')}</small></div><span>{s.preview?.rows??0} créditos · {((s.preview?.par30||0)*100).toFixed(1)}% PAR30</span><button type="button" onClick={()=>archive(s.name)}>Archivar</button></div>)}</div>}</div>
}
